monitor.alsa.rules = [

  # disable unused HDMI / GPU audio
  {
    matches = [
      { device.name = "alsa_card.pci-0000_03_00.1" },
      { device.name = "alsa_card.pci-0000_78_00.1" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  },

  # Behringer UMC22 (PCM2902) = input device
  {
    matches = [
      { device.name = "~alsa_card.*USB_Audio_CODEC.*" }
    ]
    actions = {
      update-props = {
        device.profile = "input:analog-mono"
      }
    }
  },

  # Ryzen = output device only
  {
    matches = [
      { device.name = "~alsa_card.pci-0000_78_00.6.*" }
    ]
    actions = {
      update-props = {
        device.profile = "output:analog-stereo"
      }
    }
  },

  # disable Jabra headset completely
  {
    matches = [
      { device.name = "~alsa_card.*Jabra.*" }
    ]
    actions = {
      update-props = {
        device.profile = "off"
      }
    }
  }
]
