MD013:
  line_length: 72
  heading_line_length: 72
  # code_block_line_length: 72
  code_blocks: false
  tables: false
  headings: true
  strict: true
  stern: false
first-line-h1: false
MD010:
  spaces_per_tab: 4
