vim.pack.add({
    { src = "https://github.com/romus204/tree-sitter-manager.nvim" },
}, { confirm = false })

require("tree-sitter-manager").setup({
    ensure_installed = {
        "bash",
        "commonlisp",
        "css",
        "diff",
        "gitcommit",
        "gitignore",
        "git_config",
        "git_rebase",
        "html",
        "ini",
        "javascript",
        "jsdoc",
        "json",
        "lua",
        "luadoc",
        "markdown",
        "markdown_inline",
        "printf",
        "python",
        "ssh_config",
        "tmux",
        "toml",
        "xml",
        "yaml",
        "zathurarc",
    },
    auto_install = false,
    border = "single",
    highlight = true,
    nerdfont = true,
})
