[global]
    frame_color = "#458588"
    separator_color = frame

[urgency_low]
    background = "#1d2021"
    foreground = "#ebdbb2"
    highlight = "#d79921"
    timeout = 3

[urgency_normal]
    background = "#1d2021"
    foreground = "#ebdbb2"
    timeout = 5

[urgency_critical]
    background = "#1d2021"
    foreground = "#ebdbb2"
    frame_color = "#cc241d"
    timeout = 10
