[global]
disable = [
"MD036",
"MD032",
"MD022",
"MD047" # File should end with single newline character
]

[MD013]
line-length = 72
code-blocks = false
reflow = true
# reflow-mode = "normalize"
reflow-mode = "default"
tables = false

[MD060]
enabled = true
style = "aligned"

# Generate toc
[MD073]
enabled = true

[MD007]
indent = 4

[MD051]
anchor-style = "github"

[MD033]
allowed-elements = ["details"]
