#!/bin/sh
# Author: cipherodio
# Description: nsxiv key-handler

set -eu

bm_dirs="$HOME/.config/shell/bm-dirs"

choose_dir() {
    sed 's/[[:space:]].*#.*$//;/^[[:space:]]*$/d' "$bm_dirs" |
        awk '{print $2}' |
        rofi -dmenu -i -lines 20 -p "$1" |
        sed "s|~|$HOME|g"
}

while IFS= read -r file; do
    case "$1" in
    w)
        setwallpaper "$file" &
        ;;

    c)
        destdir=$(choose_dir 'Copy file(s) to where?')

        if [ ! -d "$destdir" ]; then
            notify-send "Invalid directory, cancelled."
            exit 1
        fi

        cp "$file" "$destdir" &&
            notify-send -i "$(readlink -f "$file")" \
                "$file copied to $destdir." &
        ;;

    m)
        destdir=$(choose_dir 'Move file(s) to where?')

        if [ ! -d "$destdir" ]; then
            notify-send "Invalid directory, cancelled."
            exit 1
        fi

        mv "$file" "$destdir" &&
            notify-send -i "$(readlink -f "$file")" \
                "$file moved to $destdir." &
        ;;

    y)
        printf '%s' "$file" |
            xclip -selection clipboard &&
            notify-send "$file copied to clipboard" &
        ;;

    Y)
        readlink -f "$file" |
            xclip -selection clipboard &&
            notify-send "$(readlink -f "$file") copied to clipboard" &
        ;;

    d)
        choice=$(printf 'No\nYes\n' |
            rofi -dmenu -i -p "Really delete $file?")

        [ "$choice" = "Yes" ] &&
            rm "$file" &&
            notify-send "$file deleted."
        ;;

    r)
        convert -rotate 90 "$file" "$file"
        ;;

    R)
        convert -rotate -90 "$file" "$file"
        ;;

    f)
        convert -flop "$file" "$file"
        ;;

    g)
        ifinstalled gimp &&
            setsid -f gimp "$file"
        ;;

    i)
        notify-send "File information" "$(mediainfo "$file")"
        ;;
    esac
done
