#!/bin/sh
# Author: cipherodio
# Description: nsxiv key-handler

set -eu

bm_dirs="$HOME/.config/shell/bm-dirs"

choose_dir() {
    choice=$(sed 's/[[:space:]].*#.*$//;/^[[:space:]]*$/d' "$bm_dirs" |
        awk '{print $NF}' |
        dmenu -i -l 20 -p "$1") || return 1

    [ -z "$choice" ] && return 1

    # expand variables safely
    choice=$(printf "%s" "$choice" |
        sed -e "s|^~|$HOME|" \
            -e "s|\$HOME|$HOME|" \
            -e "s|\$NVD_DIR|${NVD_DIR:-}|")

    printf '%s\n' "$choice"
}

while IFS= read -r file; do
    case "$1" in
    w)
        setwallpaper "$file" &
        ;;

    c)
        if ! destdir=$(choose_dir 'Copy file(s) to where?'); then
            notify-send "Cancelled."
            continue
        fi

        if [ ! -d "$destdir" ]; then
            notify-send "Invalid directory, cancelled."
            continue
        fi

        cp "$file" "$destdir" &&
            notify-send -i "$(readlink -f "$file")" \
                "$file copied to $destdir." &
        ;;

    m)
        if ! destdir=$(choose_dir 'Move file(s) to where?'); then
            notify-send "Cancelled."
            continue
        fi

        if [ ! -d "$destdir" ]; then
            notify-send "Invalid directory, cancelled."
            continue
        fi

        mv "$file" "$destdir" &&
            notify-send -i "$(readlink -f "$file")" \
                "$file moved to $destdir." &
        ;;

    y)
        printf '%s' "$file" |
            xclip -selection clipboard &&
            notify-send "$file copied to clipboard" &
        ;;

    Y)
        readlink -f "$file" |
            xclip -selection clipboard &&
            notify-send "$(readlink -f "$file") copied to clipboard" &
        ;;

    d)
        choice=$(printf 'No\nYes\n' |
            rofi -dmenu -i -p "Really delete $file?")

        [ "$choice" = "Yes" ] &&
            rm "$file" &&
            notify-send "$file deleted."
        ;;

    r)
        convert -rotate 90 "$file" "$file"
        ;;

    R)
        convert -rotate -90 "$file" "$file"
        ;;

    f)
        convert -flop "$file" "$file"
        ;;

    g)
        ifinstalled gimp &&
            setsid -f gimp "$file"
        ;;

    i)
        notify-send "File information" "$(mediainfo "$file")"
        ;;
    esac
done
