# Shadows
shadow = false;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;

# Fading
fading = false;
fade-in-step = 0.03;
fade-out-step = 0.03;

# Opacity
frame-opacity = 1.0;

# Dim
# inactive-dim = 0.2;
inactive-dim-fixed = true

# Corners
corner-radius = 0

rules: ({
    match = "class_g = 'st-256color'";
    opacity = 0.8;
})

# Blur
blur-background = false

# animations = (
#     {
#         triggers = [ "geometry" ];
#         preset = "geometry-change";
#         duration = 0.2;
#     },
#     {
#         triggers = [ "open" ];
#         preset = "appear";
#         scale = 0.2;
#         duration = 0.2;
#     },
#     {
#         triggers = [ "close" ];
#         preset = "disappear";
#         scale = 0.2;
#         duration = 0.2;
#     }
# )

# General Settings
backend = "glx";
dithered-present = false;
vsync = true;
detect-rounded-corners = true;
detect-client-opacity = true;
detect-transient = true;
use-damage = false;
log-level = "warn";

# Rules
rules: (
    {
        match = "class_g = 'Alacritty' && !focused";
        dim = 0.2;
    }
)
