if vim.g.colors_name ~= nil then
    vim.cmd("highlight clear")
end
vim.g.colors_name = "gruvbox-hard-contrast"

local ui = require("utils.colors")

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.documentation", { link = "Comment" })
hi(0, "@comment.error", { bg = ui.c02, fg = ui.c01 })
hi(0, "@comment.hint", { bg = ui.c05, fg = ui.c01 })
hi(0, "@comment.note", { bg = ui.c05, fg = ui.c01 })
hi(0, "@comment.todo", { bg = ui.c04, fg = ui.c01 })
hi(0, "@comment.warning", { bg = ui.c04, fg = ui.c01 })
hi(0, "@comment.warning.gitcommit", { fg = ui.c04 })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = ui.c09 })
hi(0, "@constant.java", { fg = ui.c07 })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = ui.c11 })
hi(0, "@constructor.lua", { fg = ui.c04 })
hi(0, "@constructor.tsx", { fg = ui.c10 })
hi(0, "@constructor.typescript", { fg = ui.c10 })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = ui.c10 })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = ui.c09 })
hi(0, "@function.builtin.bash", { fg = ui.c02, italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = ui.c07 })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
-- hi(0, "@ibl.indent.char.1", { fg = "#313244", nocombine = true })
-- hi(0, "@ibl.scope.char.1", { fg = ui.c10, nocombine = true })
-- hi(0, "@ibl.scope.underline.1", { sp = ui.c12, underline = true })
-- hi(0, "@ibl.whitespace.char.1", { fg = "#45475a", nocombine = true })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.conditional.ternary", { link = "Operator" })
hi(0, "@keyword.coroutine", { link = "Keyword" })
hi(0, "@keyword.debug", { link = "Exception" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = ui.c11 })
hi(0, "@keyword.function", { fg = ui.c02 })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.modifier", { link = "Keyword" })
hi(0, "@keyword.operator", { link = "Operator" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = ui.c02 })
hi(0, "@keyword.storage", { link = "Keyword" })
hi(0, "@keyword.type", { link = "Keyword" })
hi(0, "@label.json", { fg = ui.c05 })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { fg = ui.c04 })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@module" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = ui.c12 })
hi(0, "@markup.environment", { fg = ui.c06 })
hi(0, "@markup.environment.name", { fg = ui.c05 })
hi(0, "@markup.heading", { bold = true, fg = ui.c05 })
hi(0, "@markup.heading.1.delimiter.vimdoc", {
    bg = ui.c01,
    fg = ui.c01,
    nocombine = true,
    sp = ui.c12,
    underdouble = true,
})
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(
    0,
    "@markup.heading.2.delimiter.vimdoc",
    { bg = ui.c01, fg = ui.c01, nocombine = true, sp = ui.c12, underline = true }
)
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = ui.c10, italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.label", { link = "Label" })
hi(0, "@markup.link.markdown_inline", { fg = ui.c11, italic = true, underline = true })
hi(0, "@markup.link.url", { fg = ui.c11, italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = ui.c03 })
hi(0, "@markup.list.unchecked", { fg = ui.c11 })
hi(0, "@markup.math", { fg = ui.c05 })
hi(0, "@markup.quote", { bold = true, fg = ui.c10 })
hi(0, "@markup.raw", { fg = ui.c07 })
hi(0, "@markup.strikethrough", { fg = ui.c12, strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = ui.c10 })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = ui.c10, italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = ui.c10, italic = true })
hi(0, "@number.css", { fg = ui.c09 })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = ui.c10 })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { link = "Identifier" })
hi(0, "@property.class.css", { fg = ui.c04 })
hi(0, "@property.cpp", { fg = ui.c12 })
hi(0, "@property.css", { fg = ui.c10 })
hi(0, "@property.id.css", { fg = ui.c05 })
hi(0, "@property.toml", { fg = ui.c05 })
hi(0, "@property.typescript", { fg = ui.c10 })
hi(0, "@punctuation.bracket", { fg = ui.c09 })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "Keyword" })
hi(0, "@string.documentation", { fg = ui.c07 })
hi(0, "@string.escape", { fg = ui.c06 })
hi(0, "@string.plain.css", { fg = ui.c09 })
hi(0, "@string.regex", { fg = ui.c09 })
hi(0, "@string.regexp", { fg = ui.c09 })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.path", { link = "Special" })
hi(0, "@string.special.path.gitignore", { fg = ui.c12 })
hi(0, "@string.special.symbol", { fg = ui.c04 })
hi(0, "@string.special.symbol.ruby", { fg = ui.c04 })
hi(0, "@string.special.url", { fg = ui.c12, italic = true, underline = true })
hi(0, "@symbol", { fg = ui.c04 })
hi(0, "@symbol.ruby", { fg = ui.c04 })
hi(0, "@tag", { fg = ui.c02 })
hi(0, "@tag.attribute", { fg = ui.c07, italic = true })
hi(0, "@tag.attribute.tsx", { fg = ui.c07, italic = true })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = ui.c11 })
hi(0, "@text", { fg = ui.c12 })
hi(0, "@text.danger", { bg = ui.c02, fg = ui.c01 })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = ui.c10, italic = true })
hi(0, "@text.environment", { fg = ui.c06 })
hi(0, "@text.environment.name", { fg = ui.c05 })
hi(0, "@text.literal", { fg = ui.c07 })
hi(0, "@text.math", { fg = ui.c05 })
hi(0, "@text.note", { bg = ui.c05, fg = ui.c01 })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = ui.c12, strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = ui.c10 })
hi(0, "@text.title", { bold = true, fg = ui.c05 })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = ui.c04, fg = ui.c01 })
hi(0, "@text.todo.checked", { fg = ui.c03 })
hi(0, "@text.todo.unchecked", { fg = ui.c11 })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = ui.c04, fg = ui.c01 })
hi(0, "@type.builtin", { fg = ui.c04 })
hi(0, "@type.builtin.c", { fg = ui.c04 })
hi(0, "@type.builtin.cpp", { fg = ui.c04 })
hi(0, "@type.css", { fg = ui.c10 })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = ui.c02 })
-- hi(0, "@variable", { fg = ui.c12 })
hi(0, "@variable", { fg = ui.c10 })
hi(0, "@variable.builtin", { fg = ui.c02 })
hi(0, "@variable.member", { link = "Identifier" })
hi(0, "@variable.parameter", { fg = ui.c10 })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "AlphaButtons", { fg = ui.c10 })
hi(0, "AlphaFooter", { fg = ui.c04, italic = true })
hi(0, "AlphaHeader", { fg = ui.c05 })
hi(0, "AlphaHeaderLabel", { fg = ui.c09 })
hi(0, "AlphaShortcut", { fg = ui.c03 })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = ui.c09 })
hi(0, "Character", { fg = ui.c07 })
hi(0, "CmpItemAbbr", { fg = ui.c09 })
hi(0, "CmpItemAbbrDeprecated", { fg = ui.c15, strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = ui.c12 })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = ui.c12 })
hi(0, "CmpItemKind", { fg = ui.c05 })
hi(0, "CmpItemKindClass", { fg = ui.c04 })
hi(0, "CmpItemKindColor", { fg = ui.c02 })
hi(0, "CmpItemKindConstant", { fg = ui.c09 })
hi(0, "CmpItemKindConstructor", { fg = ui.c05 })
hi(0, "CmpItemKindCopilot", { fg = ui.c07 })
hi(0, "CmpItemKindEnum", { fg = ui.c03 })
hi(0, "CmpItemKindEnumMember", { fg = ui.c02 })
hi(0, "CmpItemKindEvent", { fg = ui.c05 })
hi(0, "CmpItemKindField", { fg = ui.c03 })
hi(0, "CmpItemKindFile", { fg = ui.c05 })
hi(0, "CmpItemKindFolder", { fg = ui.c05 })
hi(0, "CmpItemKindFunction", { fg = ui.c05 })
hi(0, "CmpItemKindInterface", { fg = ui.c04 })
hi(0, "CmpItemKindKeyword", { fg = ui.c02 })
hi(0, "CmpItemKindMethod", { fg = ui.c05 })
hi(0, "CmpItemKindModule", { fg = ui.c05 })
hi(0, "CmpItemKindOperator", { fg = ui.c05 })
hi(0, "CmpItemKindProperty", { fg = ui.c03 })
hi(0, "CmpItemKindReference", { fg = ui.c02 })
hi(0, "CmpItemKindSnippet", { fg = ui.c02 })
hi(0, "CmpItemKindStruct", { fg = ui.c05 })
hi(0, "CmpItemKindText", { fg = ui.c07 })
hi(0, "CmpItemKindTypeParameter", { fg = ui.c05 })
hi(0, "CmpItemKindUnit", { fg = ui.c03 })
hi(0, "CmpItemKindValue", { fg = ui.c09 })
hi(0, "CmpItemKindVariable", { fg = ui.c04 })
hi(0, "CmpItemMenu", { fg = ui.c12 })
hi(0, "ColorColumn", { bg = ui.c15 })
hi(0, "Comment", { fg = ui.c14, italic = true })
hi(0, "Conceal", { fg = ui.c11 })
hi(0, "Conditional", { fg = ui.c02, italic = true })
hi(0, "Constant", { fg = ui.c11 })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { bg = ui.c12, fg = ui.c01 })
hi(0, "CursorColumn", { bg = ui.c15 })
hi(0, "CursorIM", { bg = ui.c12, fg = ui.c01 })
hi(0, "CursorLine", { bg = ui.c15 })
hi(0, "CursorLineNr", { fg = ui.c10 })
hi(0, "DapBreakpoint", { fg = ui.c02 })
hi(0, "DapBreakpointCondition", { fg = ui.c04 })
hi(0, "DapBreakpointRejected", { fg = ui.c02 })
hi(0, "DapLogPoint", { fg = ui.c11 })
hi(0, "DapStopped", { fg = ui.c10 })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = ui.c03 })
hi(0, "DapUIBreakpointsDisabledLine", { fg = ui.c14 })
hi(0, "DapUIBreakpointsInfo", { fg = ui.c03 })
hi(0, "DapUIBreakpointsPath", { fg = ui.c11 })
hi(0, "DapUIDecoration", { fg = ui.c11 })
hi(0, "DapUIFloatBorder", { link = "FloatBorder" })
hi(0, "DapUILineNumber", { fg = ui.c11 })
hi(0, "DapUIModifiedValue", { fg = ui.c09 })
hi(0, "DapUIPlayPause", { fg = ui.c03 })
hi(0, "DapUIRestart", { fg = ui.c03 })
hi(0, "DapUIScope", { fg = ui.c11 })
hi(0, "DapUISource", { fg = ui.c10 })
hi(0, "DapUIStepBack", { fg = ui.c05 })
hi(0, "DapUIStepInto", { fg = ui.c05 })
hi(0, "DapUIStepOut", { fg = ui.c05 })
hi(0, "DapUIStepOver", { fg = ui.c05 })
hi(0, "DapUIStop", { fg = ui.c02 })
hi(0, "DapUIStoppedThread", { fg = ui.c11 })
hi(0, "DapUIThread", { fg = ui.c03 })
hi(0, "DapUIType", { fg = ui.c02 })
hi(0, "DapUIUnavailable", { fg = ui.c14 })
hi(0, "DapUIValue", { fg = ui.c11 })
hi(0, "DapUIVariable", { fg = ui.c12 })
hi(0, "DapUIWatchesEmpty", { fg = ui.c10 })
hi(0, "DapUIWatchesError", { fg = ui.c10 })
hi(0, "DapUIWatchesValue", { fg = ui.c03 })
hi(0, "DapUIWinSelect", { fg = ui.c09 })
hi(0, "DashboardCenter", { fg = ui.c03 })
hi(0, "DashboardDesc", { fg = ui.c05 })
hi(0, "DashboardFiles", { fg = ui.c10 })
hi(0, "DashboardFooter", { fg = ui.c04, italic = true })
hi(0, "DashboardHeader", { fg = ui.c05 })
hi(0, "DashboardIcon", { bold = true, fg = ui.c06 })
hi(0, "DashboardKey", { fg = ui.c09 })
hi(0, "DashboardMruTitle", { fg = ui.c11 })
hi(0, "DashboardProjectTitle", { fg = ui.c11 })
hi(0, "DashboardShortCut", { fg = ui.c06 })
hi(0, "Delimiter", { fg = ui.c09 })
hi(0, "DiagnosticError", { fg = ui.c02 })
hi(0, "DiagnosticFloatingError", { fg = ui.c02 })
hi(0, "DiagnosticFloatingHint", { fg = ui.c07 })
hi(0, "DiagnosticFloatingInfo", { fg = ui.c11 })
hi(0, "DiagnosticFloatingOk", { fg = ui.c03 })
hi(0, "DiagnosticFloatingWarn", { fg = ui.c04 })
hi(0, "DiagnosticHint", { fg = ui.c07, italic = true })
hi(0, "DiagnosticInfo", { fg = ui.c11, italic = true })
hi(0, "DiagnosticOk", { fg = ui.c03, italic = true })
hi(0, "DiagnosticSignError", { fg = ui.c02 })
hi(0, "DiagnosticSignHint", { fg = ui.c07 })
hi(0, "DiagnosticSignInfo", { fg = ui.c11 })
hi(0, "DiagnosticSignOk", { fg = ui.c03 })
hi(0, "DiagnosticSignWarn", { fg = ui.c04 })
hi(0, "DiagnosticUnderlineError", { sp = ui.c02, underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = ui.c07, underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = ui.c11, underline = true })
hi(0, "DiagnosticUnderlineOk", { sp = ui.c03, underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = ui.c04, underline = true })
hi(0, "DiagnosticVirtualTextError", { fg = ui.c02, italic = true })
hi(0, "DiagnosticVirtualTextHint", { fg = ui.c07, italic = true })
hi(0, "DiagnosticVirtualTextInfo", { fg = ui.c11, italic = true })
hi(0, "DiagnosticVirtualTextOk", { fg = ui.c03, italic = true })
hi(0, "DiagnosticVirtualTextWarn", { fg = ui.c04, italic = true })
hi(0, "DiagnosticWarn", { fg = ui.c04 })
hi(0, "DiffAdd", { bg = ui.c03 })
hi(0, "DiffChange", { bg = ui.c07 })
hi(0, "DiffDelete", { bg = ui.c02 })
hi(0, "DiffText", { bg = ui.c04 })
hi(0, "Directory", { fg = ui.c05 })
hi(0, "DressingSelectIdx", { link = "Special" })
hi(0, "DropBarIconUISeparator", { fg = ui.c11 })
hi(0, "DropBarKindArray", { fg = ui.c12 })
hi(0, "DropBarKindBoolean", { fg = ui.c12 })
hi(0, "DropBarKindBreakStatement", { fg = ui.c12 })
hi(0, "DropBarKindCall", { fg = ui.c12 })
hi(0, "DropBarKindCaseStatement", { fg = ui.c12 })
hi(0, "DropBarKindClass", { fg = ui.c12 })
hi(0, "DropBarKindConstant", { fg = ui.c12 })
hi(0, "DropBarKindConstructor", { fg = ui.c12 })
hi(0, "DropBarKindContinueStatement", { fg = ui.c12 })
hi(0, "DropBarKindDeclaration", { fg = ui.c12 })
hi(0, "DropBarKindDelete", { fg = ui.c12 })
hi(0, "DropBarKindDoStatement", { fg = ui.c12 })
hi(0, "DropBarKindElseStatement", { fg = ui.c12 })
hi(0, "DropBarKindEnum", { fg = ui.c12 })
hi(0, "DropBarKindEnumMember", { fg = ui.c12 })
hi(0, "DropBarKindEvent", { fg = ui.c12 })
hi(0, "DropBarKindField", { fg = ui.c12 })
hi(0, "DropBarKindFile", { fg = ui.c12 })
hi(0, "DropBarKindFolder", { fg = ui.c12 })
hi(0, "DropBarKindForStatement", { fg = ui.c12 })
hi(0, "DropBarKindFunction", { fg = ui.c12 })
hi(0, "DropBarKindIdentifier", { fg = ui.c12 })
hi(0, "DropBarKindIfStatement", { fg = ui.c12 })
hi(0, "DropBarKindInterface", { fg = ui.c12 })
hi(0, "DropBarKindKeyword", { fg = ui.c12 })
hi(0, "DropBarKindList", { fg = ui.c12 })
hi(0, "DropBarKindMacro", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH1", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH2", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH3", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH4", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH5", { fg = ui.c12 })
hi(0, "DropBarKindMarkdownH6", { fg = ui.c12 })
hi(0, "DropBarKindMethod", { fg = ui.c12 })
hi(0, "DropBarKindModule", { fg = ui.c12 })
hi(0, "DropBarKindNamespace", { fg = ui.c12 })
hi(0, "DropBarKindNull", { fg = ui.c12 })
hi(0, "DropBarKindNumber", { fg = ui.c12 })
hi(0, "DropBarKindObject", { fg = ui.c12 })
hi(0, "DropBarKindOperator", { fg = ui.c12 })
hi(0, "DropBarKindPackage", { fg = ui.c12 })
hi(0, "DropBarKindProperty", { fg = ui.c12 })
hi(0, "DropBarKindReference", { fg = ui.c12 })
hi(0, "DropBarKindRepeat", { fg = ui.c12 })
hi(0, "DropBarKindScope", { fg = ui.c12 })
hi(0, "DropBarKindSpecifier", { fg = ui.c12 })
hi(0, "DropBarKindStatement", { fg = ui.c12 })
hi(0, "DropBarKindString", { fg = ui.c12 })
hi(0, "DropBarKindStruct", { fg = ui.c12 })
hi(0, "DropBarKindSwitchStatement", { fg = ui.c12 })
hi(0, "DropBarKindType", { fg = ui.c12 })
hi(0, "DropBarKindTypeParameter", { fg = ui.c12 })
hi(0, "DropBarKindUnit", { fg = ui.c12 })
hi(0, "DropBarKindValue", { fg = ui.c12 })
hi(0, "DropBarKindVariable", { fg = ui.c12 })
hi(0, "DropBarKindWhileStatement", { fg = ui.c12 })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
-- hi(0, "EndOfBuffer", { fg = ui.c01 })
hi(0, "Error", { fg = ui.c02 })
hi(0, "ErrorMsg", { bold = true, fg = ui.c02, italic = true })
hi(0, "Exception", { fg = ui.c02 })
hi(0, "FloatBorder", { fg = ui.c05 })
hi(0, "FloatTitle", { fg = ui.c07 })
hi(0, "FoldColumn", { fg = ui.c14 })
hi(0, "Folded", { bg = ui.c01, fg = ui.c14 })
hi(0, "Function", { fg = ui.c05 })
hi(0, "GitSignsAdd", { fg = ui.c03 })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = ui.c04 })
hi(0, "GitSignsCurrentLineBlame", { fg = ui.c11 })
hi(0, "GitSignsDelete", { fg = ui.c02 })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
-- hi(0, "GitSignsStagedAdd", { fg = "#537150" })
-- hi(0, "GitSignsStagedAddCul", { fg = "#537150" })
-- hi(0, "GitSignsStagedAddLn", { bg = "#364143" })
-- hi(0, "GitSignsStagedAddNr", { fg = "#537150" })
-- hi(0, "GitSignsStagedChange", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedChangeCul", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedChangeLn", { bg = "#25293c" })
-- hi(0, "GitSignsStagedChangeNr", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedChangedelete", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedChangedeleteCul", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedChangedeleteLn", { bg = "#25293c" })
-- hi(0, "GitSignsStagedChangedeleteNr", { fg = "#7c7157" })
-- hi(0, "GitSignsStagedDelete", { fg = "#794554" })
-- hi(0, "GitSignsStagedDeleteCul", { fg = "#794554" })
-- hi(0, "GitSignsStagedDeleteNr", { fg = "#794554" })
-- hi(0, "GitSignsStagedTopdelete", { fg = "#794554" })
-- hi(0, "GitSignsStagedTopdeleteCul", { fg = "#794554" })
-- hi(0, "GitSignsStagedTopdeleteNr", { fg = "#794554" })
hi(0, "HopNextKey", { bold = true, ctermfg = 198, fg = ui.c02 })
hi(0, "HopNextKey1", { bold = true, ctermfg = 45, fg = ui.c11 })
hi(0, "HopNextKey2", { ctermfg = 33, fg = ui.c05 })
hi(0, "HopUnmatched", { ctermfg = 242, fg = ui.c16, sp = ui.c16 })
hi(0, "IblIndent", { fg = ui.c15 })
hi(0, "IblScope", { fg = ui.c12 })
hi(0, "IblWhitespace", { fg = ui.c15 })
hi(0, "Identifier", { fg = ui.c05 })
hi(0, "IncSearch", { bg = ui.c01, fg = ui.c09, bold = true, reverse = true })
hi(0, "Include", { fg = ui.c02 })
hi(0, "IndentBlankLineContextChar", { fg = ui.c12 })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = ui.c02 })
hi(0, "Label", { fg = ui.c04, bold = true })
hi(0, "LineNr", { fg = ui.c16 })
hi(0, "LspCodeLens", { fg = ui.c14 })
hi(0, "LspDiagnosticsDefaultError", { fg = ui.c02 })
hi(0, "LspDiagnosticsDefaultHint", { fg = ui.c07 })
hi(0, "LspDiagnosticsDefaultInformation", { fg = ui.c11 })
hi(0, "LspDiagnosticsDefaultWarning", { fg = ui.c04 })
hi(0, "LspDiagnosticsError", { fg = ui.c02 })
hi(0, "LspDiagnosticsHint", { fg = ui.c07 })
hi(0, "LspDiagnosticsInformation", { fg = ui.c11 })
hi(0, "LspDiagnosticsUnderlineError", { sp = ui.c02, underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = ui.c07, underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = ui.c11, underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = ui.c04, underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = ui.c02, italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = ui.c07, italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = ui.c11, italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = ui.c04, italic = true })
hi(0, "LspDiagnosticsWarning", { fg = ui.c04 })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { fg = ui.c14, italic = true })
hi(0, "LspReferenceRead", { bg = ui.c01 })
hi(0, "LspReferenceText", { bg = ui.c01 })
hi(0, "LspReferenceWrite", { bg = ui.c01 })
hi(0, "LspSignatureActiveParameter", { fg = ui.c09 })
hi(0, "Macro", { fg = ui.c02 })
-- hi(0, "MatchParen", { bg = ui.c01, bold = true, fg = ui.c09 })
hi(0, "MatchParen", { bg = "none", bold = true, fg = ui.c09, underline = true })
hi(0, "MiniIndentscopeSymbol", { fg = ui.c10 })
hi(0, "ModeMsg", { bold = true, fg = ui.c12 })
hi(0, "MoreMsg", { fg = ui.c05 })
hi(0, "MsgSeparator", {})
hi(0, "NavicSeparator", { link = "Normal" })
-- hi(0, "NeoTreeDimText", { fg = ui.c11 })
-- hi(0, "NeoTreeDirectoryIcon", { fg = ui.c05 })
-- hi(0, "NeoTreeDirectoryName", { fg = ui.c05 })
-- hi(0, "NeoTreeExpander", { fg = "#6c7086" })
-- hi(0, "NeoTreeFileNameOpened", { fg = ui.c06 })
-- hi(0, "NeoTreeFilterTerm", { bold = true, fg = ui.c03 })
-- hi(0, "NeoTreeFloatBorder", { link = "FloatBorder" })
-- hi(0, "NeoTreeFloatTitle", { link = "FloatTitle" })
-- hi(0, "NeoTreeGitAdded", { fg = ui.c03 })
-- hi(0, "NeoTreeGitConflict", { fg = ui.c02 })
-- hi(0, "NeoTreeGitDeleted", { fg = ui.c02 })
-- hi(0, "NeoTreeGitIgnored", { fg = "#6c7086" })
-- hi(0, "NeoTreeGitModified", { fg = ui.c04 })
-- hi(0, "NeoTreeGitStaged", { fg = ui.c03 })
-- hi(0, "NeoTreeGitUnstaged", { fg = ui.c02 })
-- hi(0, "NeoTreeGitUntracked", { fg = ui.c02 })
-- hi(0, "NeoTreeIndentMarker", { fg = "#6c7086" })
-- hi(0, "NeoTreeModified", { fg = ui.c09 })
-- hi(0, "NeoTreeNormal", { bg = "#181825", fg = ui.c12 })
-- hi(0, "NeoTreeNormalNC", { bg = "#181825", fg = ui.c12 })
-- hi(0, "NeoTreeRootName", { bold = true, fg = ui.c05 })
-- hi(0, "NeoTreeStatusLineNC", { bg = "#181825", fg = "#181825" })
-- hi(0, "NeoTreeSymbolicLinkTarget", { fg = ui.c06 })
-- hi(0, "NeoTreeTabActive", { bg = "#181825", bold = true, fg = ui.c10 })
-- hi(0, "NeoTreeTabInactive", { bg = ui.c01, fg = "#6c7086" })
-- hi(0, "NeoTreeTabSeparatorActive", { bg = "#181825", fg = "#181825" })
-- hi(0, "NeoTreeTabSeparatorInactive", { bg = ui.c01, fg = ui.c01 })
-- hi(0, "NeoTreeTitleBar", { bg = ui.c05, fg = "#181825" })
-- hi(0, "NeoTreeVertSplit", { bg = ui.c01, fg = ui.c01 })
-- hi(0, "NeoTreeWinSeparator", { bg = ui.c01, fg = ui.c01 })
hi(0, "NeogitBranch", { bold = true, fg = ui.c09 })
hi(0, "NeogitChangeAdded", { bold = true, fg = ui.c03 })
hi(0, "NeogitChangeBothModified", { bold = true, fg = ui.c04 })
hi(0, "NeogitChangeCopied", { bold = true, fg = ui.c06 })
hi(0, "NeogitChangeDeleted", { bold = true, fg = ui.c02 })
hi(0, "NeogitChangeModified", { bold = true, fg = ui.c05 })
hi(0, "NeogitChangeNewFile", { bold = true, fg = ui.c03 })
hi(0, "NeogitChangeRenamed", { bold = true, fg = ui.c02 })
hi(0, "NeogitChangeUpdated", { bold = true, fg = ui.c09 })
hi(0, "NeogitCommitViewHeader", { bg = ui.c01, fg = ui.c11 })
hi(0, "NeogitDiffAdd", { bg = ui.c01, fg = ui.c03 })
hi(0, "NeogitDiffAddHighlight", { bg = ui.c01, fg = ui.c07 })
hi(0, "NeogitDiffContext", { bg = ui.c01 })
hi(0, "NeogitDiffContextHighlight", { bg = ui.c01 })
hi(0, "NeogitDiffDelete", { bg = ui.c01, fg = ui.c02 })
hi(0, "NeogitDiffDeleteHighlight", { bg = ui.c01, fg = ui.c06 })
hi(0, "NeogitDiffHeader", { bg = ui.c01, bold = true, fg = ui.c05 })
hi(0, "NeogitDiffHeaderHighlight", { bg = ui.c01, bold = true, fg = ui.c09 })
hi(0, "NeogitFilePath", { fg = ui.c05, italic = true })
hi(0, "NeogitGraphBlue", { fg = ui.c05 })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = ui.c05 })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = ui.c05 })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = ui.c11 })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = ui.c03 })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = ui.c10 })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = ui.c02 })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = ui.c04 })
hi(0, "NeogitGraphCyan", { fg = ui.c05 })
hi(0, "NeogitGraphGray", { fg = ui.c11 })
hi(0, "NeogitGraphGreen", { fg = ui.c03 })
hi(0, "NeogitGraphOrange", { fg = ui.c09 })
hi(0, "NeogitGraphPurple", { fg = ui.c10 })
hi(0, "NeogitGraphRed", { fg = ui.c02 })
hi(0, "NeogitGraphWhite", { fg = ui.c01 })
hi(0, "NeogitGraphYellow", { fg = ui.c04 })
hi(0, "NeogitHunkHeader", { bg = ui.c01, fg = ui.c14 })
hi(0, "NeogitHunkHeaderHighlight", { bg = ui.c01, fg = ui.c05 })
hi(0, "NeogitNotificationError", { fg = ui.c02 })
hi(0, "NeogitNotificationInfo", { fg = ui.c05 })
hi(0, "NeogitNotificationWarning", { fg = ui.c04 })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = ui.c10 })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = ui.c10 })
hi(0, "NeogitPopupOptionKey", { fg = ui.c10 })
hi(0, "NeogitPopupSwitchKey", { fg = ui.c10 })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = ui.c02 })
hi(0, "NeogitRecentcommits", { bold = true, fg = ui.c02 })
hi(0, "NeogitRemote", { bold = true, fg = ui.c03 })
hi(0, "NeogitSectionHeader", { bold = true, fg = ui.c02 })
hi(0, "NeogitStagedchanges", { bold = true, fg = ui.c02 })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = ui.c02 })
hi(0, "NeogitTagDistance", { fg = ui.c05 })
hi(0, "NeogitTagName", { fg = ui.c04 })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = ui.c02 })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = ui.c02 })
hi(0, "NeogitUnpushedTo", { bold = true, fg = ui.c10 })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = ui.c02 })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = ui.c02 })
hi(0, "NeogitWinSeparator", { link = "WinSeparator" })
hi(0, "NoiceCmdline", { fg = ui.c12 })
hi(0, "NoiceCmdlineIcon", { fg = ui.c11, italic = true })
hi(0, "NoiceCmdlineIconSearch", { fg = ui.c04 })
hi(0, "NoiceCmdlinePopupBorder", { fg = ui.c10 })
hi(0, "NoiceCmdlinePopupBorderSearch", { fg = ui.c04 })
hi(0, "NoiceConfirmBorder", { fg = ui.c05 })
hi(0, "NoiceFormatProgressDone", { bg = ui.c13, fg = ui.c11 })
hi(0, "NoiceFormatProgressTodo", { bg = ui.c01, fg = ui.c11 })
hi(0, "NoiceMini", { blend = 0, fg = ui.c11 })
hi(0, "NonText", { fg = ui.c16 })
hi(0, "Normal", { bg = ui.c01, fg = ui.c12 })
hi(0, "NormalFloat", { bg = ui.c01, fg = ui.c12 })
hi(0, "NormalNC", { bg = ui.c01, fg = ui.c12 })
hi(0, "NormalSB", { bg = ui.c13, fg = ui.c12 })
hi(0, "Number", { fg = ui.c09 })
hi(0, "NvimTreeEmptyFolderName", { fg = ui.c05 })
hi(0, "NvimTreeFolderIcon", { fg = ui.c05 })
hi(0, "NvimTreeFolderName", { fg = ui.c05 })
hi(0, "NvimTreeGitDeleted", { fg = ui.c02 })
hi(0, "NvimTreeGitDirty", { fg = ui.c04 })
hi(0, "NvimTreeGitNew", { fg = ui.c05 })
hi(0, "NvimTreeImageFile", { fg = ui.c12 })
hi(0, "NvimTreeIndentMarker", { fg = ui.c11 })
hi(0, "NvimTreeNormal", { bg = ui.c13, fg = ui.c12 })
hi(0, "NvimTreeOpenedFile", { fg = ui.c06 })
hi(0, "NvimTreeOpenedFolderName", { fg = ui.c05 })
hi(0, "NvimTreeRootFolder", { bold = true, fg = ui.c10 })
hi(0, "NvimTreeSpecialFile", { fg = ui.c04 })
hi(0, "NvimTreeStatuslineNc", { bg = ui.c13, fg = ui.c13 })
hi(0, "NvimTreeSymlink", { fg = ui.c06 })
hi(0, "NvimTreeWinSeparator", { bg = ui.c01, fg = ui.c01 })
hi(0, "Operator", { fg = ui.c11 })
hi(0, "Pmenu", { bg = ui.c15, fg = ui.c12 })
hi(0, "PmenuSbar", { bg = ui.c15 })
hi(0, "PmenuSel", { bg = ui.c15, bold = true })
hi(0, "PmenuThumb", { bg = ui.c16 })
hi(0, "PreProc", { fg = ui.c06 })
hi(0, "Question", { fg = ui.c05 })
hi(0, "QuickFixLine", { fg = ui.c10, bold = true })
hi(0, "RainbowDelimiterBlue", { fg = ui.c05 })
hi(0, "RainbowDelimiterCyan", { fg = ui.c07 })
hi(0, "RainbowDelimiterGreen", { fg = ui.c03 })
hi(0, "RainbowDelimiterOrange", { fg = ui.c09 })
hi(0, "RainbowDelimiterRed", { fg = ui.c02 })
hi(0, "RainbowDelimiterViolet", { fg = ui.c02 })
hi(0, "RainbowDelimiterYellow", { fg = ui.c04 })
-- hi(0, "RenderMarkdownBullet", { fg = ui.c11 })
-- hi(0, "RenderMarkdownCode", { bg = ui.c13 })
-- hi(0, "RenderMarkdownCodeInline", { bg = ui.c15 })
-- hi(0, "RenderMarkdownError", { fg = ui.c02 })
-- hi(0, "RenderMarkdownH1", { fg = ui.c02 })
-- hi(0, "RenderMarkdownH1Bg", { bg = "#5e3f53" })
-- hi(0, "RenderMarkdownH2", { fg = ui.c09 })
-- hi(0, "RenderMarkdownH2Bg", { bg = "#604b49" })
-- hi(0, "RenderMarkdownH3", { fg = ui.c04 })
-- hi(0, "RenderMarkdownH3Bg", { bg = "#605955" })
-- hi(0, "RenderMarkdownH4", { fg = ui.c03 })
-- hi(0, "RenderMarkdownH4Bg", { bg = "#475951" })
-- hi(0, "RenderMarkdownH5", { fg = ui.c11 })
-- hi(0, "RenderMarkdownH5Bg", { bg = "#385167" })
-- hi(0, "RenderMarkdownH6", { fg = ui.c10 })
-- hi(0, "RenderMarkdownH6Bg", { bg = "#4b4e6c" })
-- hi(0, "RenderMarkdownHint", { fg = ui.c07 })
-- hi(0, "RenderMarkdownInfo", { fg = ui.c11 })
-- hi(0, "RenderMarkdownSuccess", { fg = ui.c03 })
-- hi(0, "RenderMarkdownTableHead", { fg = ui.c05 })
-- hi(0, "RenderMarkdownTableRow", { fg = ui.c10 })
-- hi(0, "RenderMarkdownWarn", { fg = ui.c04 })
hi(0, "Repeat", { fg = ui.c02 })
hi(0, "Search", { bg = ui.c01, fg = ui.c04, bold = true, reverse = true })
hi(0, "SignColumn", { fg = ui.c16 })
hi(0, "SignColumnSB", { bg = ui.c01, fg = ui.c14 })
hi(0, "Special", { fg = ui.c06 })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = ui.c02, undercurl = true })
hi(0, "SpellCap", { sp = ui.c04, undercurl = true })
hi(0, "SpellLocal", { sp = ui.c05, undercurl = true })
hi(0, "SpellRare", { sp = ui.c03, undercurl = true })
hi(0, "Statement", { fg = ui.c02 })
-- hi(0, "StatusLine", { bg = ui.c01 })
-- hi(0, "StatusLineNC", { bg = ui.c01, fg = ui.c14 })
hi(0, "StorageClass", { fg = ui.c04 })
hi(0, "String", { fg = ui.c03 })
hi(0, "Structure", { fg = ui.c04 })
hi(0, "Substitute", { bg = ui.c13, fg = ui.c06 })
hi(0, "TabLine", { link = "TabLineFill" })
hi(0, "TabLineFill", { bg = ui.c01, fg = ui.c16 })
hi(0, "TabLineSel", { bg = ui.c01, fg = ui.c03 })
hi(0, "Tag", { bold = true, fg = ui.c10 })
hi(0, "TermCursor", { bg = ui.c12, fg = ui.c01 })
hi(0, "TermCursorNC", { bg = ui.c09, fg = ui.c01 })
hi(0, "Title", { bold = true, fg = ui.c05 })
hi(0, "Todo", { bg = ui.c04, bold = true, fg = ui.c01 })
hi(0, "TreesitterContextBottom", { sp = ui.c13, underline = true })
hi(0, "TreesitterContextLineNumber", { bg = ui.c13, fg = ui.c15 })
hi(0, "Type", { fg = ui.c04 })
-- hi(0, "UfoFoldedEllipsis", { bg = ui.c05, fg = "#11111b" })
-- hi(0, "UfoFoldedFg", { fg = ui.c10 })
hi(0, "VertSplit", { fg = ui.c02 })
hi(0, "Visual", { bg = ui.c16, bold = true })
hi(0, "VisualNOS", { bg = ui.c16, bold = true })
hi(0, "WarningMsg", { fg = ui.c04 })
hi(0, "WhichKeyGroup", { fg = ui.c09 })
hi(0, "WhichKeySeparator", { fg = ui.c12 })
hi(0, "Whitespace", { fg = ui.c16 })
hi(0, "WildMenu", { bg = ui.c16 })
hi(0, "WinBar", { fg = ui.c12 })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = ui.c02 })
hi(0, "debugBreakpoint", { bg = ui.c01, fg = ui.c02 })
hi(0, "debugPC", { bg = ui.c13 })
hi(0, "diffAdded", { fg = ui.c03 })
hi(0, "diffChanged", { fg = ui.c05 })
hi(0, "diffFile", { fg = ui.c05 })
hi(0, "diffIndexLine", { fg = ui.c07 })
hi(0, "diffLine", { fg = ui.c11 })
hi(0, "diffNewFile", { fg = ui.c09 })
hi(0, "diffOldFile", { fg = ui.c04 })
hi(0, "diffRemoved", { fg = ui.c02 })
hi(0, "gitcommitSummary", { fg = ui.c12, italic = true })
hi(0, "healthError", { fg = ui.c02 })
hi(0, "healthSuccess", { fg = ui.c07 })
hi(0, "healthWarning", { fg = ui.c04 })
hi(0, "htmlBold", { bold = true })
hi(0, "htmlBoldItalic", { bold = true, italic = true })
hi(0, "htmlBoldUnderline", { bold = true, underline = true })
hi(0, "htmlBoldUnderlineItalic", { bold = true, italic = true, underline = true })
hi(0, "htmlH1", { bold = true, fg = ui.c06 })
hi(0, "htmlH2", { bold = true, fg = ui.c05 })
hi(0, "htmlItalic", { italic = true })
hi(0, "htmlStrike", { strikethrough = true })
hi(0, "htmlUnderline", { underline = true })
hi(0, "htmlUnderlineItalic", { italic = true, underline = true })
-- hi(0, "illuminatedCurWord", { bg = "#45475a" })
-- hi(0, "illuminatedWord", { bg = "#45475a" })
hi(0, "lCursor", { bg = ui.c12, fg = ui.c01 })
hi(0, "markdownCode", { fg = ui.c04 })
hi(0, "markdownCodeBlock", { fg = ui.c07 })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = ui.c09 })
hi(0, "markdownLinkText", { fg = ui.c05, underline = true })
hi(0, "mkdCodeDelimiter", { bg = ui.c01, fg = ui.c12 })
hi(0, "mkdCodeEnd", { bold = true, fg = ui.c04 })
hi(0, "mkdCodeStart", { bold = true, fg = ui.c04 })
hi(0, "qfFileName", { fg = ui.c05 })
hi(0, "qfLineNr", { fg = ui.c04 })
hi(0, "rainbow1", { fg = ui.c02 })
hi(0, "rainbow2", { fg = ui.c09 })
hi(0, "rainbow3", { fg = ui.c04 })
hi(0, "rainbow4", { fg = ui.c03 })
hi(0, "rainbow5", { fg = ui.c11 })
hi(0, "rainbow6", { fg = ui.c10 })
hi(0, "zshKSHFunction", { link = "Function" })
hi(0, "BlinkCmpDoc", { bg = ui.c13 })
hi(0, "BlinkCmpMenu", { bg = ui.c13, fg = ui.c12 })
hi(0, "BlinkCmpMenuSelection", { bg = ui.c05, fg = ui.c01 })
hi(0, "BlinkCmpDocSeparator", { bg = ui.c13 })
hi(0, "BlinkCmpDocCursorLine", { bg = ui.c13 })
hi(0, "BlinkCmpDocBorder", { bg = ui.c13 })
hi(0, "TimestampHighlight", { fg = ui.c12 })

-- Last Modified: Wed, 07 Jan 2026 12:51:09 AM
