-- Made with 'mini.colors' module of https://nvim-mini.org/mini.nvim

if vim.g.colors_name ~= nil then
    vim.cmd("highlight clear")
end
vim.g.colors_name = "nord"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = "#d8dee9" })
hi(0, "@attribute.builtin", { link = "Special" })
hi(0, "@attribute.phpdoc", { fg = "#81a1c1" })
hi(0, "@boolean", { fg = "#81a1c1" })
hi(0, "@character", { fg = "#a3be8c" })
hi(0, "@character.printf", { fg = "#ebcb8b" })
hi(0, "@character.special", { fg = "#ebcb8b" })
hi(0, "@comment", { fg = "#616e88" })
hi(0, "@comment.error", { fg = "#bf616a" })
hi(0, "@comment.note", { fg = "#81a1c1" })
hi(0, "@comment.todo", { fg = "#81a1c1" })
hi(0, "@comment.warning", { fg = "#ebcb8b" })
hi(0, "@conditional", { link = "@keyword.conditional" })
hi(0, "@constant", { fg = "#d8dee9" })
hi(0, "@constant.builtin", { fg = "#81a1c1" })
hi(0, "@constant.git_rebase", { fg = "#8fbcbb" })
hi(0, "@constant.macro", { fg = "#81a1c1" })
hi(0, "@constructor", { fg = "#88c0d0" })
hi(0, "@debug", { link = "@keyword.debug" })
hi(0, "@define", { link = "@keyword.directive.define" })
hi(0, "@diff.delta", { link = "DiffChange" })
hi(0, "@diff.minus", { link = "DiffDelete" })
hi(0, "@diff.plus", { link = "DiffAdd" })
hi(0, "@error", { bg = "#bf616a" })
hi(0, "@exception", { link = "@keyword.exception" })
hi(0, "@field", { link = "@variable.member" })
hi(0, "@float", { link = "@number.float" })
hi(0, "@function", { fg = "#88c0d0", italic = true })
hi(0, "@function.builtin", { fg = "#88c0d0" })
hi(0, "@function.call", { fg = "#88c0d0" })
hi(0, "@function.macro", { fg = "#81a1c1" })
hi(0, "@function.method", { fg = "#88c0d0" })
hi(0, "@function.method.call", { fg = "#88c0d0" })
hi(0, "@include", { link = "@keyword.import" })
hi(0, "@keyword", { fg = "#81a1c1" })
hi(0, "@keyword.conditional", { fg = "#81a1c1" })
hi(0, "@keyword.debug", { fg = "#d8dee9" })
hi(0, "@keyword.directive", { fg = "#81a1c1" })
hi(0, "@keyword.directive.define", { fg = "#81a1c1" })
hi(0, "@keyword.exception", { fg = "#81a1c1" })
hi(0, "@keyword.function", { fg = "#81a1c1", italic = true })
hi(0, "@keyword.import", { fg = "#81a1c1" })
hi(0, "@keyword.operator", { fg = "#81a1c1" })
hi(0, "@keyword.repeat", { fg = "#81a1c1" })
hi(0, "@keyword.return", { fg = "#81a1c1" })
hi(0, "@keyword.storage", { fg = "#81a1c1" })
hi(0, "@label", { fg = "#8fbcbb" })
hi(0, "@lsp.mod.deprecated", { link = "DiagnosticDeprecated" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.field", { link = "@field" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { link = "@type" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@structure" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeParameter", { link = "@parameter" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup.environment", { fg = "#8fbcbb" })
hi(0, "@markup.environment.name", { fg = "#81a1c1" })
hi(0, "@markup.heading", { bold = true, fg = "#88c0d0" })
hi(
    0,
    "@markup.heading.1.delimiter.vimdoc",
    { nocombine = true, sp = "#d8dee9", underdouble = true }
)
hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#81a1c1" })
hi(
    0,
    "@markup.heading.2.delimiter.vimdoc",
    { nocombine = true, sp = "#d8dee9", underline = true }
)
hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#b48ead" })
hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#a3be8c" })
hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#ebcb8b" })
hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#d08770" })
hi(0, "@markup.heading.6.markdown", { bold = true, fg = "#bf616a" })
hi(0, "@markup.link", { fg = "#8fbcbb" })
hi(0, "@markup.link.label", { fg = "#ebcb8b" })
hi(0, "@markup.link.label.markdown_inline", { fg = "#a3be8c" })
hi(0, "@markup.link.url", { fg = "#a3be8c", sp = "#a3be8c", underline = true })
hi(0, "@markup.list", { fg = "#81a1c1" })
hi(0, "@markup.list.checked", { fg = "#8fbcbb" })
hi(0, "@markup.list.unchecked", { fg = "#88c0d0" })
hi(0, "@markup.math", { fg = "#8fbcbb" })
hi(0, "@markup.raw", { fg = "#8fbcbb" })
hi(0, "@method", { link = "@function.method" })
hi(0, "@method.call", { link = "@function.method.call" })
hi(0, "@module", { fg = "#d8dee9" })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { link = "@module" })
hi(0, "@number", { fg = "#b48ead" })
hi(0, "@number.float", { fg = "#b48ead" })
hi(0, "@operator", { fg = "#81a1c1" })
hi(0, "@parameter", { link = "@variable.parameter" })
hi(0, "@preproc", { link = "@keyword.directive" })
hi(0, "@property", { fg = "#d8dee9" })
hi(0, "@property.yaml", { fg = "#8fbcbb" })
hi(0, "@punctuation.bracket", { fg = "#88c0d0" })
hi(0, "@punctuation.delimiter", { fg = "#eceff4" })
hi(0, "@punctuation.special", { link = "@markup.list" })
hi(0, "@repeat", { link = "@keyword.repeat" })
hi(0, "@storageclass", { link = "@keyword.storage" })
hi(0, "@string", { fg = "#a3be8c" })
hi(0, "@string.escape", { fg = "#ebcb8b" })
hi(0, "@string.regex", { link = "@string.regexp" })
hi(0, "@string.regexp", { fg = "#ebcb8b" })
hi(0, "@string.special", { link = "@markup.link.label" })
hi(0, "@string.special.symbol", { fg = "#d8dee9" })
hi(0, "@string.special.url", { link = "Underlined" })
hi(0, "@symbol", { link = "@string.special.symbol" })
hi(0, "@tag", { fg = "#81a1c1" })
hi(0, "@tag.attribute", { fg = "#8fbcbb" })
hi(0, "@tag.builtin", { link = "Special" })
hi(0, "@tag.delimiter", { fg = "#81a1c1" })
hi(0, "@text", { fg = "#d8dee9" })
hi(0, "@text.danger", { link = "@comment.error" })
hi(0, "@text.diff.add", { link = "DiffAdd" })
hi(0, "@text.diff.delete", { link = "DiffDelete" })
hi(0, "@text.emphasis", { link = "@markup.italic" })
hi(0, "@text.environment", { link = "@markup.environment" })
hi(0, "@text.environment.name", { link = "@markup.environment.name" })
hi(0, "@text.literal", { link = "@markup.raw" })
hi(0, "@text.math", { link = "@markup.math" })
hi(0, "@text.note", { link = "@comment.note" })
hi(0, "@text.phpdoc", { fg = "#616e88" })
hi(0, "@text.reference", { link = "@markup.link" })
hi(0, "@text.strike", { link = "@markup.strikethrough" })
hi(0, "@text.strong", { link = "@markup.strong" })
hi(0, "@text.title", { link = "@markup.heading" })
hi(0, "@text.todo", { link = "@comment.todo" })
hi(0, "@text.underline", { link = "@markup.underline" })
hi(0, "@text.uri", { link = "@markup.link.url" })
hi(0, "@text.warning", { link = "@comment.warning" })
hi(0, "@type", { fg = "#8fbcbb" })
hi(0, "@type.builtin", { fg = "#81a1c1" })
hi(0, "@type.definition", { fg = "#8fbcbb" })
hi(0, "@type.qualifier", { fg = "#81a1c1" })
hi(0, "@variable", { fg = "#d8dee9" })
hi(0, "@variable.builtin", { fg = "#81a1c1" })
hi(0, "@variable.member", { fg = "#d8dee9" })
hi(0, "@variable.parameter", { fg = "#88c0d0" })
hi(0, "@variable.parameter.builtin", { link = "Special" })
hi(0, "Added", { link = "DiffAdd" })
hi(0, "AerialArray", { link = "@lsp.type.variable" })
hi(0, "AerialArrayIcon", { link = "AerialArray" })
hi(0, "AerialBoolean", { link = "@boolean" })
hi(0, "AerialBooleanIcon", { link = "AerialBoolean" })
hi(0, "AerialClass", { link = "@lsp.type.class" })
hi(0, "AerialClassIcon", { link = "AerialClass" })
hi(0, "AerialConstant", { link = "@constant" })
hi(0, "AerialConstantIcon", { link = "AerialConstant" })
hi(0, "AerialConstructor", { link = "@constructor" })
hi(0, "AerialConstructorIcon", { link = "AerialConstructor" })
hi(0, "AerialEnum", { link = "@lsp.type.enum" })
hi(0, "AerialEnumIcon", { link = "AerialEnum" })
hi(0, "AerialEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "AerialEnumMemberIcon", { link = "AerialEnumMember" })
hi(0, "AerialEvent", { link = "@lsp.type.event" })
hi(0, "AerialEventIcon", { link = "AerialEvent" })
hi(0, "AerialField", { link = "@field" })
hi(0, "AerialFieldIcon", { link = "AerialField" })
hi(0, "AerialFile", { link = "@include" })
hi(0, "AerialFileIcon", { link = "AerialFile" })
hi(0, "AerialFunction", { link = "@lsp.type.function" })
hi(0, "AerialFunctionIcon", { link = "AerialFunction" })
hi(0, "AerialInterface", { link = "@lsp.type.interface" })
hi(0, "AerialInterfaceIcon", { link = "AerialInterface" })
hi(0, "AerialKey", { link = "@variable" })
hi(0, "AerialKeyIcon", { link = "AerialKey" })
hi(0, "AerialLine", { bg = "#3b4252" })
hi(0, "AerialLineNC", { bg = "#3b4252" })
hi(0, "AerialMethod", { link = "@lsp.type.method" })
hi(0, "AerialMethodIcon", { link = "AerialMethod" })
hi(0, "AerialModule", { link = "@include" })
hi(0, "AerialModuleIcon", { link = "AerialModule" })
hi(0, "AerialNamespace", { link = "@lsp.type.namespace" })
hi(0, "AerialNamespaceIcon", { link = "AerialNamespace" })
hi(0, "AerialNull", { link = "@variable" })
hi(0, "AerialNullIcon", { link = "AerialNull" })
hi(0, "AerialNumber", { link = "@number" })
hi(0, "AerialNumberIcon", { link = "AerialNumber" })
hi(0, "AerialObject", { link = "@variable" })
hi(0, "AerialObjectIcon", { link = "AerialObject" })
hi(0, "AerialOperator", { link = "@operator" })
hi(0, "AerialOperatorIcon", { link = "AerialOperator" })
hi(0, "AerialPackage", { link = "@include" })
hi(0, "AerialPackageIcon", { link = "AerialPackage" })
hi(0, "AerialProperty", { link = "@lsp.type.property" })
hi(0, "AerialPropertyIcon", { link = "AerialProperty" })
hi(0, "AerialString", { link = "@string" })
hi(0, "AerialStringIcon", { link = "AerialString" })
hi(0, "AerialStruct", { link = "@lsp.type.struct" })
hi(0, "AerialStructIcon", { link = "AerialStruct" })
hi(0, "AerialTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "AerialTypeParameterIcon", { link = "AerialTypeParameter" })
hi(0, "AerialVariable", { link = "@variable" })
hi(0, "AerialVariableIcon", { link = "AerialVariable" })
hi(0, "BlinkCmpDocBorder", { fg = "#3b4252" })
hi(0, "BlinkCmpGhostText", { fg = "#616e88" })
hi(0, "BlinkCmpKind", { fg = "#81a1c1" })
hi(0, "BlinkCmpKindArray", { link = "@lsp.type.array" })
hi(0, "BlinkCmpKindBoolean", { link = "@lsp.type.boolean" })
hi(0, "BlinkCmpKindClass", { link = "@lsp.type.class" })
hi(0, "BlinkCmpKindCodeium", { fg = "#a3be8c" })
hi(0, "BlinkCmpKindColor", { link = "@lsp.type.color" })
hi(0, "BlinkCmpKindConstant", { link = "@lsp.type.constant" })
hi(0, "BlinkCmpKindConstructor", { link = "@lsp.type.constructor" })
hi(0, "BlinkCmpKindCopilot", { fg = "#a3be8c" })
hi(0, "BlinkCmpKindEnum", { link = "@lsp.type.enum" })
hi(0, "BlinkCmpKindEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "BlinkCmpKindEvent", { link = "@lsp.type.event" })
hi(0, "BlinkCmpKindField", { link = "@lsp.type.field" })
hi(0, "BlinkCmpKindFile", { link = "@lsp.type.file" })
hi(0, "BlinkCmpKindFolder", { link = "@lsp.type.folder" })
hi(0, "BlinkCmpKindFunction", { link = "@lsp.type.function" })
hi(0, "BlinkCmpKindInterface", { link = "@lsp.type.interface" })
hi(0, "BlinkCmpKindKey", { link = "@lsp.type.key" })
hi(0, "BlinkCmpKindKeyword", { link = "@lsp.type.keyword" })
hi(0, "BlinkCmpKindMethod", { link = "@lsp.type.method" })
hi(0, "BlinkCmpKindModule", { link = "@lsp.type.module" })
hi(0, "BlinkCmpKindNamespace", { link = "@lsp.type.namespace" })
hi(0, "BlinkCmpKindNull", { link = "@lsp.type.null" })
hi(0, "BlinkCmpKindNumber", { link = "@lsp.type.number" })
hi(0, "BlinkCmpKindObject", { link = "@lsp.type.object" })
hi(0, "BlinkCmpKindOperator", { link = "@lsp.type.operator" })
hi(0, "BlinkCmpKindPackage", { link = "@lsp.type.package" })
hi(0, "BlinkCmpKindProperty", { link = "@lsp.type.property" })
hi(0, "BlinkCmpKindReference", { link = "@lsp.type.reference" })
hi(0, "BlinkCmpKindSnippet", { fg = "#a3be8c" })
hi(0, "BlinkCmpKindString", { link = "@lsp.type.string" })
hi(0, "BlinkCmpKindStruct", { link = "@lsp.type.struct" })
hi(0, "BlinkCmpKindText", { link = "@lsp.type.text" })
hi(0, "BlinkCmpKindTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "BlinkCmpKindUnit", { link = "@lsp.type.unit" })
hi(0, "BlinkCmpKindValue", { link = "@lsp.type.value" })
hi(0, "BlinkCmpKindVariable", { link = "@lsp.type.variable" })
hi(0, "BlinkCmpLabelDeprecated", { fg = "#616e88" })
hi(0, "BlinkCmpLabelMatch", { bold = true })
hi(0, "BlinkCmpMenuBorder", { fg = "#3b4252" })
hi(0, "BlinkCmpMenuSelection", { bg = "#434c5e" })
hi(0, "BlinkCmpSignatureHelpBorder", { fg = "#3b4252" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#81a1c1" })
hi(0, "BufferCurrent", { bg = "#434c5e" })
hi(0, "BufferCurrentERROR", { bg = "#434c5e", fg = "#bf616a" })
hi(0, "BufferCurrentHINT", { bg = "#434c5e", fg = "#81a1c1" })
hi(0, "BufferCurrentINFO", { bg = "#434c5e", fg = "#88c0d0" })
hi(0, "BufferCurrentIndex", { bg = "#434c5e" })
hi(0, "BufferCurrentMod", { bg = "#434c5e", fg = "#ebcb8b", italic = true })
hi(0, "BufferCurrentSign", { bg = "#434c5e", fg = "#81a1c1" })
hi(0, "BufferCurrentTarget", { bg = "#434c5e", bold = true, fg = "#bf616a" })
hi(0, "BufferCurrentWARN", { bg = "#434c5e", fg = "#ebcb8b" })
hi(0, "BufferInactive", { bg = "#2e3440", fg = "#616e88" })
hi(0, "BufferInactiveERROR", { bg = "#2e3440", fg = "#684651" })
hi(0, "BufferInactiveHINT", { bg = "#2e3440", fg = "#4f6074" })
hi(0, "BufferInactiveINFO", { bg = "#2e3440", fg = "#526c7a" })
hi(0, "BufferInactiveIndex", { bg = "#2e3440", fg = "#616e88" })
hi(0, "BufferInactiveMod", { bg = "#2e3440", fg = "#7a705e", italic = true })
hi(0, "BufferInactiveSign", { bg = "#2e3440", fg = "#2e3440" })
hi(0, "BufferInactiveTarget", { bg = "#2e3440", bold = true, fg = "#bf616a" })
hi(0, "BufferInactiveWARN", { bg = "#2e3440", fg = "#7a705e" })
hi(0, "BufferTabpage", { bg = "#2e3440" })
hi(0, "BufferTabpageFill", { bg = "#2e3440", fg = "#2e3440" })
hi(0, "BufferTabpages", { bg = "#2e3440" })
hi(0, "BufferVisible", { bg = "#3b4252" })
hi(0, "BufferVisibleERROR", { bg = "#3b4252", fg = "#bf616a" })
hi(0, "BufferVisibleHINT", { bg = "#3b4252", fg = "#81a1c1" })
hi(0, "BufferVisibleINFO", { bg = "#3b4252", fg = "#88c0d0" })
hi(0, "BufferVisibleIndex", { bg = "#3b4252" })
hi(0, "BufferVisibleMod", { bg = "#3b4252", fg = "#ebcb8b", italic = true })
hi(0, "BufferVisibleSign", { bg = "#3b4252", fg = "#81a1c1" })
hi(0, "BufferVisibleTarget", { bg = "#3b4252", bold = true, fg = "#bf616a" })
hi(0, "BufferVisibleWARN", { bg = "#3b4252", fg = "#ebcb8b" })
hi(0, "Changed", { link = "DiffChange" })
hi(0, "Character", { fg = "#a3be8c" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#616e88" })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#88c0d0" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#88c0d0" })
hi(0, "CmpItemKind", { fg = "#81a1c1" })
hi(0, "CmpItemKindClass", { fg = "#88c0d0" })
hi(0, "CmpItemKindFunction", { fg = "#b48ead" })
hi(0, "CmpItemKindInterface", { fg = "#88c0d0" })
hi(0, "CmpItemKindMethod", { fg = "#b48ead" })
hi(0, "CmpItemKindSnippet", { fg = "#a3be8c" })
hi(0, "CmpItemKindText", { fg = "#d8dee9" })
hi(0, "CmpItemKindVariable", { fg = "#88c0d0" })
hi(0, "CodeiumSuggestion", { fg = "#616e88" })
hi(0, "ColorColumn", { bg = "#3b4252" })
hi(0, "Comment", { fg = "#616e88" })
hi(0, "Conceal", {})
hi(0, "Conditional", { fg = "#81a1c1" })
hi(0, "Constant", { fg = "#d8dee9" })
hi(0, "CurSearch", { link = "IncSearch" })
hi(0, "Cursor", { fg = "#d8dee9", reverse = true })
hi(0, "CursorColumn", { bg = "#3b4252" })
hi(0, "CursorIM", { fg = "#e5e9f0", reverse = true })
hi(0, "CursorLine", { bg = "#3b4252" })
hi(0, "CursorLineNr", { bold = true, fg = "#d8dee9" })
hi(0, "CursorPos", { bg = "#2e3440", fg = "#616e88" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#a3be8c" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#616e88" })
hi(0, "DapUIBreakpointsInfo", { fg = "#a3be8c" })
hi(0, "DapUIBreakpointsPath", { fg = "#88c0d0" })
hi(0, "DapUIDecoration", { fg = "#88c0d0" })
hi(0, "DapUIEndofBuffer", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "DapUIFloatBorder", { fg = "#88c0d0" })
hi(0, "DapUILineNumber", { fg = "#88c0d0" })
hi(0, "DapUIModifiedValue", { bold = true, fg = "#88c0d0" })
hi(0, "DapUIPlayPause", { fg = "#a3be8c" })
hi(0, "DapUIPlayPauseNC", { bg = "#2e3440", fg = "#74876e" })
hi(0, "DapUIRestart", { fg = "#a3be8c" })
hi(0, "DapUIRestartNC", { bg = "#2e3440", fg = "#74876e" })
hi(0, "DapUIScope", { fg = "#88c0d0" })
hi(0, "DapUISource", { fg = "#b48ead" })
hi(0, "DapUIStepBack", { fg = "#88c0d0" })
hi(0, "DapUIStepBackNC", { bg = "#2e3440", fg = "#648896" })
hi(0, "DapUIStepInto", { fg = "#88c0d0" })
hi(0, "DapUIStepIntoNC", { bg = "#2e3440", fg = "#648896" })
hi(0, "DapUIStepOut", { fg = "#88c0d0" })
hi(0, "DapUIStepOutNC", { bg = "#2e3440", fg = "#648896" })
hi(0, "DapUIStepOver", { fg = "#88c0d0" })
hi(0, "DapUIStepOverNC", { bg = "#2e3440", fg = "#648896" })
hi(0, "DapUIStop", { fg = "#bf616a" })
hi(0, "DapUIStopNC", { bg = "#2e3440", fg = "#854f59" })
hi(0, "DapUIStoppedThread", { fg = "#88c0d0" })
hi(0, "DapUIThread", { fg = "#a3be8c" })
hi(0, "DapUIType", { fg = "#b48ead" })
hi(0, "DapUIUnavailable", { fg = "#616e88" })
hi(0, "DapUIUnavailableNC", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "DapUIWatchesEmpty", { fg = "#bf616a" })
hi(0, "DapUIWatchesError", { fg = "#bf616a" })
hi(0, "DapUIWatchesValue", { fg = "#a3be8c" })
hi(0, "DapUIWinSelect", { bold = true, fg = "#88c0d0" })
hi(0, "Debug", { fg = "#d8dee9" })
hi(0, "Define", { fg = "#81a1c1" })
hi(0, "Delimiter", { fg = "#eceff4" })
hi(0, "DiagnosticError", { fg = "#bf616a" })
hi(0, "DiagnosticHint", { fg = "#81a1c1" })
hi(0, "DiagnosticInfo", { fg = "#88c0d0" })
hi(0, "DiagnosticOk", { fg = "#a3be8c" })
hi(0, "DiagnosticUnderlineError", { sp = "#bf616a", undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#81a1c1", undercurl = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#88c0d0", undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#ebcb8b", undercurl = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#3d3944", fg = "#bf616a" })
hi(0, "DiagnosticVirtualTextHint", { bg = "#363f4d", fg = "#81a1c1" })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#37424e", fg = "#88c0d0" })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#414348", fg = "#ebcb8b" })
hi(0, "DiagnosticWarn", { fg = "#ebcb8b" })
hi(0, "DiffAdd", { bg = "#3b4252", fg = "#a3be8c", reverse = true })
hi(0, "DiffChange", { bg = "#3b4252", fg = "#ebcb8b", reverse = true })
hi(0, "DiffDelete", { bg = "#3b4252", fg = "#bf616a", reverse = true })
hi(0, "DiffText", { bg = "#3b4252", fg = "#81a1c1", reverse = true })
hi(0, "DiffviewFilePanelDeletions", { fg = "#bf616a" })
hi(0, "DiffviewFilePanelInsertions", { fg = "#a3be8c" })
hi(0, "DiffviewStatusModified", { fg = "#ebcb8b" })
hi(0, "Directory", { fg = "#88c0d0" })
hi(0, "EndOfBuffer", { fg = "#3b4252" })
hi(0, "Error", { bg = "#bf616a" })
hi(0, "ErrorMsg", { bg = "#bf616a", fg = "#d8dee9" })
hi(0, "Exception", { fg = "#81a1c1" })
hi(0, "FlashCurrent", { bg = "#434c5e", fg = "#d8dee9", underline = true })
hi(0, "FlashLabel", { bg = "#ebcb8b", bold = true, fg = "#2e3440" })
hi(0, "FlashMatch", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "Float", { fg = "#b48ead" })
hi(0, "FloatBorder", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "FoldColumn", { bg = "#2e3440", fg = "#4c566a" })
hi(0, "Folded", { bg = "#3b4252", fg = "#eceff4" })
hi(0, "Function", { fg = "#88c0d0", italic = true })
hi(0, "FzfLuaBackdrop", { bg = "#000000" })
hi(0, "FzfLuaBorder", { fg = "#616e88" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#88c0d0" })
hi(0, "FzfLuaBufFlagCur", { fg = "#bf616a" })
hi(0, "FzfLuaBufNr", { fg = "#ebcb8b" })
hi(0, "FzfLuaHeaderBind", { fg = "#88c0d0" })
hi(0, "FzfLuaHeaderText", { fg = "#5e81ac" })
hi(0, "FzfLuaLivePrompt", { fg = "#ebcb8b" })
hi(0, "FzfLuaLiveSym", { fg = "#bf616a" })
hi(0, "FzfLuaPathColNr", { fg = "#88c0d0" })
hi(0, "FzfLuaPathLineNr", { fg = "#a3be8c" })
hi(0, "FzfLuaTabMarker", { fg = "#ebcb8b" })
hi(0, "FzfLuaTabTitle", { fg = "#81a1c1" })
hi(0, "FzfLuaTitle", { bold = true, fg = "#d8dee9" })
hi(0, "GitAddSign", { bg = "#2e3440", fg = "#a3be8c" })
hi(0, "GitChangeSign", { bg = "#2e3440", fg = "#ebcb8b" })
hi(0, "GitDeleteSign", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "GitDots", { bg = "#2e3440", fg = "#81a1c1" })
hi(0, "GitGraphAuthor", { fg = "#a3be8c" })
hi(0, "GitGraphBranch1", { fg = "#5e81ac" })
hi(0, "GitGraphBranch2", { fg = "#a3be8c" })
hi(0, "GitGraphBranch3", { fg = "#bf616a" })
hi(0, "GitGraphBranch4", { fg = "#ebcb8b" })
hi(0, "GitGraphBranch5", { fg = "#88c0d0" })
hi(0, "GitGraphBranchMsg", { fg = "#d8dee9" })
hi(0, "GitGraphBranchName", { fg = "#bf616a" })
hi(0, "GitGraphBranchTag", { fg = "#ebcb8b" })
hi(0, "GitGraphHash", { fg = "#b48ead" })
hi(0, "GitGraphTimestamp", { fg = "#88c0d0" })
hi(0, "GitGutterAdd", { fg = "#a3be8c" })
hi(0, "GitGutterChange", { fg = "#ebcb8b" })
hi(0, "GitGutterDelete", { fg = "#bf616a" })
hi(0, "GitHeadSign", { bg = "#2e3440", fg = "#616e88" })
hi(0, "GitLoose", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "GitProj", { bg = "#2e3440", fg = "#ebcb8b" })
hi(0, "GitSignsAdd", { fg = "#a3be8c" })
hi(0, "GitSignsAddLn", { fg = "#a3be8c" })
hi(0, "GitSignsAddNr", { fg = "#a3be8c" })
hi(0, "GitSignsChange", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeLn", { fg = "#ebcb8b" })
hi(0, "GitSignsChangeNr", { fg = "#ebcb8b" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#616e88" })
hi(0, "GitSignsDelete", { fg = "#bf616a" })
hi(0, "GitSignsDeleteLn", { fg = "#bf616a" })
hi(0, "GitSignsDeleteNr", { fg = "#bf616a" })
hi(0, "GitSignsStagedAdd", { fg = "#515f46" })
hi(0, "GitSignsStagedAddCul", { fg = "#515f46" })
hi(0, "GitSignsStagedAddLn", { fg = "#515f46" })
hi(0, "GitSignsStagedAddNr", { fg = "#515f46" })
hi(0, "GitSignsStagedChange", { fg = "#756545" })
hi(0, "GitSignsStagedChangeCul", { fg = "#756545" })
hi(0, "GitSignsStagedChangeLn", { fg = "#756545" })
hi(0, "GitSignsStagedChangeNr", { fg = "#756545" })
hi(0, "GitSignsStagedChangedelete", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteCul", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteLn", { fg = "#756545" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#756545" })
hi(0, "GitSignsStagedDelete", { fg = "#5f3035" })
hi(0, "GitSignsStagedDeleteCul", { fg = "#5f3035" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdelete", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdeleteCul", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdeleteLn", { fg = "#5f3035" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#5f3035" })
hi(0, "GitSignsStagedUntracked", { fg = "#515f46" })
hi(0, "GitSignsStagedUntrackedCul", { fg = "#515f46" })
hi(0, "GitSignsStagedUntrackedLn", { fg = "#515f46" })
hi(0, "GitSignsStagedUntrackedNr", { fg = "#515f46" })
hi(0, "GlanceBorderTop", { link = "GlancePreviewBorderBottom" })
hi(0, "GlanceFoldIcon", { fg = "#d8dee9" })
hi(0, "GlanceIndent", { fg = "#4c566a" })
hi(0, "GlanceListBorderBottom", { link = "GlancePreviewBorderBottom" })
hi(0, "GlanceListCount", { fg = "#b48ead" })
hi(0, "GlanceListCursorLine", { bg = "#434c5e" })
hi(0, "GlanceListEndOfBuffer", { bg = "#3b4252" })
hi(0, "GlanceListFilename", { fg = "#8fbcbb" })
hi(0, "GlanceListFilepath", { fg = "#616e88" })
hi(0, "GlanceListMatch", { bg = "#4c566a" })
hi(0, "GlanceListNormal", { bg = "#3b4252" })
hi(0, "GlancePreviewBorderBottom", { bg = "#2e3440", fg = "#3b4252" })
hi(0, "GlancePreviewCursorLine", { link = "CursorLine" })
hi(0, "GlancePreviewEndOfBuffer", { bg = "#2e3440" })
hi(0, "GlancePreviewLineNr", { link = "LineNr" })
hi(0, "GlancePreviewMatch", { bg = "#4c566a" })
hi(0, "GlancePreviewNormal", { bg = "#2e3440" })
hi(0, "GlancePreviewSignColumn", { link = "SignColumn" })
hi(0, "GlanceWinBarFilename", { bg = "#434c5e", fg = "#8fbcbb" })
hi(0, "GlanceWinBarFilepath", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "GlanceWinBarTitle", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "HighlightRedo", { link = "Search" })
hi(0, "HighlightUndo", { link = "Search" })
hi(0, "Identifier", { fg = "#d8dee9" })
hi(0, "IlluminatedWordRead", { bg = "#4c566a" })
hi(0, "IlluminatedWordText", { bg = "#4c566a" })
hi(0, "IlluminatedWordWrite", { bg = "#4c566a" })
hi(0, "IncSearch", { bg = "#5b7a88", fg = "#d8dee9" })
hi(0, "Include", { fg = "#81a1c1" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#81a1c1" })
hi(0, "LSPError", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "LSPHint", { bg = "#2e3440", fg = "#88c0d0" })
hi(0, "LSPInfo", { bg = "#2e3440", fg = "#81a1c1" })
hi(0, "LSPProjBracket", { bg = "#2e3440", fg = "#a3be8c" })
hi(0, "LSPSingleBracket", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "LSPStat", { bg = "#2e3440", fg = "#81a1c1" })
hi(0, "LSPWarn", { bg = "#2e3440", fg = "#ebcb8b" })
hi(0, "Label", { fg = "#81a1c1" })
hi(0, "LeapBackdrop", { link = "Comment" })
hi(0, "LeapLabel", { bg = "#ebcb8b", bold = true, fg = "#2e3440" })
hi(
    0,
    "LeapLabelPrimary",
    { bg = "#a3be8c", bold = true, fg = "#3b4252", nocombine = true }
)
hi(
    0,
    "LeapLabelSecondary",
    { bg = "#b48ead", bold = true, fg = "#3b4252", nocombine = true }
)
hi(
    0,
    "LeapLabelSelected",
    { bg = "#ebcb8b", bold = true, fg = "#3b4252", nocombine = true }
)
hi(0, "LeapMatch", { bg = "#8fbcbb", bold = true, fg = "#3b4252", nocombine = true })
hi(0, "LineNr", { fg = "#4c566a" })
hi(0, "LspCodeLens", { fg = "#4c566a" })
hi(0, "LspInlayHint", { fg = "#4c566a" })
hi(0, "LspSignatureActiveParameter", { bg = "#434c5e", bold = true })
hi(0, "Macro", { link = "Define" })
hi(0, "MarkviewCode", { bg = "#3b4252" })
hi(0, "MarkviewHeading1", { bg = "#3a4248", fg = "#a3be8c" })
hi(0, "MarkviewHeading1Sign", { fg = "#a3be8c" })
hi(0, "MarkviewHeading2", { bg = "#414348", fg = "#ebcb8b" })
hi(0, "MarkviewHeading2Sign", { fg = "#ebcb8b" })
hi(0, "MarkviewHeading3", { bg = "#3b3d4b", fg = "#b48ead" })
hi(0, "MarkviewHeading3Sign", { fg = "#b48ead" })
hi(0, "MarkviewHeading4", { bg = "#38424c", fg = "#8fbcbb" })
hi(0, "MarkviewHeading4Sign", { fg = "#8fbcbb" })
hi(0, "MarkviewHeading5", { bg = "#37424e", fg = "#88c0d0" })
hi(0, "MarkviewHeading5Sign", { fg = "#88c0d0" })
hi(0, "MarkviewHeading6", { bg = "#333c4b", fg = "#5e81ac" })
hi(0, "MarkviewHeading6Sign", { fg = "#5e81ac" })
hi(0, "MarkviewInlineCode", { bg = "#3b4252" })
hi(0, "MatchParen", { bg = "#4c566a", bold = true })
hi(0, "MiniIndentscopePrefix", { nocombine = true })
hi(0, "MiniIndentscopeSymbol", { fg = "#5e81ac" })
hi(0, "ModeCmd", { bg = "#81a1c1", fg = "#2e3440" })
hi(0, "ModeInsert", { bg = "#ebcb8b", fg = "#2e3440" })
hi(0, "ModeMsg", { fg = "#d8dee9" })
hi(0, "ModeNormal", { bg = "#a3be8c", fg = "#2e3440" })
hi(0, "ModeReplace", { bg = "#b48ead", fg = "#2e3440" })
hi(0, "ModeVisual", { bg = "#b48ead", fg = "#2e3440" })
hi(0, "MoreMsg", { fg = "#88c0d0" })
hi(0, "MsgSeparator", {})
hi(0, "NavicIconsArray", { link = "@variable" })
hi(0, "NavicIconsBoolean", { link = "@boolean" })
hi(0, "NavicIconsClass", { link = "@lsp.type.class" })
hi(0, "NavicIconsConstant", { link = "@constant" })
hi(0, "NavicIconsConstructor", { link = "@constructor" })
hi(0, "NavicIconsEnum", { link = "@lsp.type.enum" })
hi(0, "NavicIconsEnumMember", { link = "@lsp.type.enumMember" })
hi(0, "NavicIconsEvent", { link = "@lsp.type.event" })
hi(0, "NavicIconsField", { link = "@lsp.type.field" })
hi(0, "NavicIconsFile", { link = "@include" })
hi(0, "NavicIconsFunction", { link = "@lsp.type.function" })
hi(0, "NavicIconsInterface", { link = "@lsp.type.interface" })
hi(0, "NavicIconsKey", { link = "@variable" })
hi(0, "NavicIconsKeyword", { link = "@keyword" })
hi(0, "NavicIconsMethod", { link = "@lsp.type.method" })
hi(0, "NavicIconsModule", { link = "@include" })
hi(0, "NavicIconsNamespace", { link = "@lsp.type.namespace" })
hi(0, "NavicIconsNull", { link = "@variable" })
hi(0, "NavicIconsNumber", { link = "@number" })
hi(0, "NavicIconsObject", { link = "@lsp.type.class" })
hi(0, "NavicIconsOperator", { link = "@lsp.type.operator" })
hi(0, "NavicIconsPackage", { link = "@include" })
hi(0, "NavicIconsProperty", { link = "@lsp.type.property" })
hi(0, "NavicIconsString", { link = "@string" })
hi(0, "NavicIconsStruct", { link = "@lsp.type.struct" })
hi(0, "NavicIconsTypeParameter", { link = "@lsp.type.typeParameter" })
hi(0, "NavicIconsVariable", { link = "@variable" })
hi(0, "NavicSeparator", { bg = "#434c5e", fg = "#81a1c1" })
hi(0, "NavicText", { link = "@text" })
hi(0, "NeoTreeDimText", { fg = "#4c566a" })
hi(0, "NeoTreeDirectoryIcon", { fg = "#81a1c1" })
hi(0, "NeoTreeDirectoryName", { fg = "#d8dee9" })
hi(0, "NeoTreeDotfile", { fg = "#616e88" })
hi(0, "NeoTreeFadeText1", { fg = "#4c566a" })
hi(0, "NeoTreeFadeText2", { fg = "#434c5e" })
hi(0, "NeoTreeFileIcon", { fg = "#d8dee9" })
hi(0, "NeoTreeFileName", { fg = "#d8dee9" })
hi(0, "NeoTreeGitConflict", { fg = "#bf616a" })
hi(0, "NeoTreeGitUnstaged", { fg = "#d08770", italic = true })
hi(0, "NeoTreeGitUntracked", { fg = "#a3be8c", italic = true })
hi(0, "NeoTreeIndentMarker", { fg = "#434c5e" })
hi(0, "NeoTreeMessage", { fg = "#4c566a", italic = true })
hi(0, "NeoTreeModified", { fg = "#ebcb8b" })
hi(0, "NeoTreeRootName", { bold = true, fg = "#d8dee9" })
hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#81a1c1" })
hi(0, "NeoTreeTabActive", { bg = "#434c5e", bold = true, fg = "#d8dee9" })
hi(0, "NeoTreeTabInactive", { bg = "#2e3440", fg = "#616e88" })
hi(0, "NeoTreeTabSeparatorActive", { bg = "#2e3440", fg = "#434c5e" })
hi(0, "NeoTreeTabSeparatorInactive", { bg = "#2e3440", fg = "#2e3440" })
hi(0, "NeogitContextHighlight", { bg = "#3b4252", fg = "#81a1c1" })
hi(0, "NeogitDiffAdd", { bg = "#3b4252", fg = "#a3be8c" })
hi(0, "NeogitDiffAddCursor", { bg = "#2e3440", fg = "#a3be8c" })
hi(0, "NeogitDiffAddHighlight", { bg = "#3b4252", fg = "#a3be8c" })
hi(0, "NeogitDiffChange", { bg = "#3b4252", fg = "#ebcb8b" })
hi(0, "NeogitDiffContext", { bg = "#2e3440", fg = "#81a1c1" })
hi(0, "NeogitDiffContextCursor", { bg = "#2e3440", fg = "#81a1c1" })
hi(0, "NeogitDiffContextHighlight", { bg = "#3b4252", fg = "#81a1c1" })
hi(0, "NeogitDiffDelete", { bg = "#3b4252", fg = "#bf616a" })
hi(0, "NeogitDiffDeleteCursor", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#3b4252", fg = "#bf616a" })
hi(0, "NeogitDiffText", { bg = "#3b4252", fg = "#81a1c1" })
hi(0, "NeogitHunkHeader", { bg = "#4c566a", fg = "#d8dee9" })
hi(0, "NonText", { fg = "#434c5e" })
hi(0, "Normal", { fg = "#d8dee9" })
hi(0, "NormalFloat", { bg = "#2e3440", fg = "#d8dee9" })
hi(0, "NotifierContentDim", { fg = "#616e88" })
hi(0, "NotifierTitle", { bold = true, fg = "#8fbcbb" })
hi(0, "NotifyBackground", { bg = "#2e3440" })
hi(0, "NotifyDEBUGBorder", { fg = "#3b4252" })
hi(0, "NotifyDEBUGIcon", { fg = "#d8dee9" })
hi(0, "NotifyDEBUGTitle", { fg = "#d8dee9" })
hi(0, "NotifyERRORBorder", { fg = "#774b55" })
hi(0, "NotifyERRORIcon", { fg = "#bf616a" })
hi(0, "NotifyERRORTitle", { fg = "#bf616a" })
hi(0, "NotifyINFOBorder", { fg = "#586b81" })
hi(0, "NotifyINFOIcon", { fg = "#81a1c1" })
hi(0, "NotifyINFOTitle", { fg = "#81a1c1" })
hi(0, "NotifyTRACEBorder", { fg = "#716177" })
hi(0, "NotifyTRACEIcon", { fg = "#b48ead" })
hi(0, "NotifyTRACETitle", { fg = "#b48ead" })
hi(0, "NotifyWARNBorder", { fg = "#8d8066" })
hi(0, "NotifyWARNIcon", { fg = "#ebcb8b" })
hi(0, "NotifyWARNTitle", { fg = "#ebcb8b" })
hi(0, "Number", { fg = "#b48ead" })
hi(0, "NvimTreeFolderIcon", { fg = "#81a1c1" })
hi(0, "NvimTreeGitDeleted", { fg = "#bf616a" })
hi(0, "NvimTreeGitDirty", { fg = "#ebcb8b" })
hi(0, "NvimTreeGitIgnored", { fg = "#616e88" })
hi(0, "NvimTreeGitNew", { fg = "#a3be8c" })
hi(0, "NvimTreeImageFile", { fg = "#d8dee9" })
hi(0, "NvimTreeIndentMarker", { fg = "#81a1c1" })
hi(0, "NvimTreeNormal", { fg = "#d8dee9" })
hi(0, "NvimTreeNormalNC", { fg = "#d8dee9" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#d8dee9" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d8dee9" })
hi(0, "NvimTreeSpecialFile", { fg = "#ebcb8b", underline = true })
hi(0, "NvimTreeSymlink", { fg = "#81a1c1" })
hi(0, "NvimTreeWinSeparator", { fg = "#3b4252" })
hi(0, "Operator", { fg = "#81a1c1" })
hi(0, "Pmenu", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "PmenuSbar", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "PmenuSel", { bg = "#434c5e", fg = "#d8dee9" })
hi(0, "PmenuThumb", { bg = "#4c566a", fg = "#88c0d0" })
hi(0, "PreProc", { fg = "#81a1c1" })
hi(0, "Question", { fg = "#d8dee9" })
hi(0, "QuickFixLine", { fg = "#d8dee9", reverse = true })
hi(0, "RainbowDelimiterBlue", { fg = "#5e81ac" })
hi(0, "RainbowDelimiterCyan", { fg = "#88c0d0" })
hi(0, "RainbowDelimiterGreen", { fg = "#d08770" })
hi(0, "RainbowDelimiterOrange", { fg = "#a3be8c" })
hi(0, "RainbowDelimiterRed", { fg = "#bf616a" })
hi(0, "RainbowDelimiterViolet", { fg = "#b48ead" })
hi(0, "RainbowDelimiterYellow", { fg = "#ebcb8b" })
hi(0, "Removed", { link = "DiffDelete" })
hi(0, "RenderMarkdownBullet", { fg = "#81a1c1" })
hi(0, "RenderMarkdownH1Bg", { bg = "#3f4a5a" })
hi(0, "RenderMarkdownH2Bg", { bg = "#494656" })
hi(0, "RenderMarkdownH3Bg", { bg = "#45504f" })
hi(0, "RenderMarkdownH4Bg", { bg = "#54524f" })
hi(0, "RenderMarkdownH5Bg", { bg = "#4e454a" })
hi(0, "RenderMarkdownH6Bg", { bg = "#4b3d48" })
hi(0, "RenderMarkdownQuote", { fg = "#616e88" })
hi(0, "RenderMarkdownTodo", { fg = "#d8dee9" })
hi(0, "Repeat", { fg = "#81a1c1" })
hi(0, "Search", { bg = "#40505d" })
hi(0, "SignColumn", { fg = "#3b4252" })
hi(0, "SnacksDashboardDir", { link = "Comment" })
hi(0, "SnacksPickerBufFlags", { link = "Comment" })
hi(0, "SnacksPickerDir", { link = "Comment" })
hi(0, "SnacksPickerGitStatus", { link = "Comment" })
hi(0, "SnacksPickerGitStatusIgnored", { link = "Comment" })
hi(0, "SnacksPickerGitStatusUntracked", { link = "Comment" })
hi(0, "SnacksPickerKeymapRhs", { link = "Comment" })
hi(0, "SnacksPickerPathHidden", { link = "Comment" })
hi(0, "SnacksPickerPathIgnored", { link = "Comment" })
hi(0, "SnacksPickerTotals", { link = "Comment" })
hi(0, "SpacerHL", { bg = "#2e3440" })
hi(0, "Special", { fg = "#d8dee9" })
hi(0, "SpecialChar", { fg = "#ebcb8b" })
hi(0, "SpecialComment", { fg = "#88c0d0" })
hi(0, "SpecialKey", { fg = "#4c566a" })
hi(0, "SpellBad", { sp = "#bf616a", undercurl = true })
hi(0, "SpellCap", { sp = "#ebcb8b", undercurl = true })
hi(0, "SpellLocal", { sp = "#e5e9f0", undercurl = true })
hi(0, "SpellRare", { bg = "#2e3440", fg = "#eceff4", sp = "#eceff4", undercurl = true })
hi(0, "Statement", { fg = "#81a1c1" })
hi(0, "StatusLine", { bg = "#434c5e", fg = "#88c0d0" })
hi(0, "StatusLineNC", { bg = "#4c566a", fg = "#d8dee9" })
hi(0, "StorageClass", { fg = "#81a1c1" })
hi(0, "String", { fg = "#a3be8c" })
hi(0, "Structure", { fg = "#81a1c1" })
hi(0, "TabLine", { fg = "#d8dee9" })
hi(0, "TabLineFill", { bg = "#3b4252", fg = "#d8dee9" })
hi(0, "TabLineSel", { bg = "#4c566a", fg = "#88c0d0" })
hi(0, "Tag", { fg = "#d8dee9" })
hi(0, "TelescopeBorder", { fg = "#616e88" })
hi(0, "TelescopeMatching", { bold = true, fg = "#88c0d0" })
hi(0, "TelescopePromptCounter", { fg = "#616e88" })
hi(0, "TelescopeTitle", { bold = true, fg = "#d8dee9" })
hi(0, "TermCursor", { fg = "#d8dee9", reverse = true })
hi(0, "TermCursorNC", { fg = "#4c566a", reverse = true })
hi(0, "Title", { bold = true, fg = "#d8dee9" })
hi(0, "Todo", { fg = "#ebcb8b" })
hi(0, "TodoBgFIX", { bg = "#bf616a", bold = true, fg = "#000000" })
hi(0, "TodoBgHACK", { bg = "#ebcb8b", bold = true, fg = "#000000" })
hi(0, "TodoBgNOTE", { bg = "#81a1c1", bold = true, fg = "#000000" })
hi(0, "TodoBgPERF", { bg = "#d8dee9", bold = true, fg = "#000000" })
hi(0, "TodoBgTEST", { bg = "#d8dee9", bold = true, fg = "#000000" })
hi(0, "TodoBgTODO", { bg = "#88c0d0", bold = true, fg = "#000000" })
hi(0, "TodoBgWARN", { bg = "#ebcb8b", bold = true, fg = "#000000" })
hi(0, "TodoFgFIX", { fg = "#bf616a" })
hi(0, "TodoFgHACK", { fg = "#ebcb8b" })
hi(0, "TodoFgNOTE", { fg = "#81a1c1" })
hi(0, "TodoFgPERF", { fg = "#d8dee9" })
hi(0, "TodoFgTEST", { fg = "#d8dee9" })
hi(0, "TodoFgTODO", { fg = "#88c0d0" })
hi(0, "TodoFgWARN", { fg = "#ebcb8b" })
hi(0, "TodoSignFIX", { fg = "#bf616a" })
hi(0, "TodoSignHACK", { fg = "#ebcb8b" })
hi(0, "TodoSignNOTE", { fg = "#81a1c1" })
hi(0, "TodoSignPERF", { fg = "#d8dee9" })
hi(0, "TodoSignTEST", { fg = "#d8dee9" })
hi(0, "TodoSignTODO", { fg = "#88c0d0" })
hi(0, "TodoSignWARN", { fg = "#ebcb8b" })
hi(0, "TroubleCount", { bg = "#4c566a", fg = "#88c0d0" })
hi(0, "TroubleIndent", { fg = "#616e88" })
hi(0, "TroubleLocation", { fg = "#616e88" })
hi(0, "TroubleNormal", { fg = "#d8dee9" })
hi(0, "TroubleText", { fg = "#d8dee9" })
hi(0, "Type", { fg = "#81a1c1" })
hi(0, "Typedef", { fg = "#81a1c1" })
hi(0, "VertSplit", { fg = "#3b4252" })
hi(0, "VimwikiHR", { fg = "#ebcb8b" })
hi(0, "VimwikiHeader1", { bold = true, fg = "#5e81ac" })
hi(0, "VimwikiHeader2", { bold = true, fg = "#81a1c1" })
hi(0, "VimwikiHeader3", { bold = true, fg = "#88c0d0" })
hi(0, "VimwikiHeader4", { bold = true, fg = "#8fbcbb" })
hi(0, "VimwikiHeader5", { bold = true, fg = "#616e88" })
hi(0, "VimwikiHeader6", { bold = true, fg = "#4c566a" })
hi(0, "VimwikiHeaderChar", { fg = "#616e88" })
hi(0, "VimwikiLink", { fg = "#a3be8c" })
hi(0, "VimwikiList", { fg = "#81a1c1" })
hi(0, "VimwikiMarkers", { fg = "#5e81ac" })
hi(0, "VimwikiTag", { fg = "#a3be8c" })
hi(0, "Visual", { bg = "#434c5e" })
hi(0, "VisualNOS", { bg = "#434c5e" })
hi(0, "WarningMsg", { bg = "#ebcb8b", fg = "#2e3440" })
hi(0, "WhichKey", { bold = true, fg = "#88c0d0" })
hi(0, "WhichKeyDesc", { fg = "#d8dee9" })
hi(0, "WhichKeyFloat", { bg = "#3b4252" })
hi(0, "WhichKeyGroup", { fg = "#81a1c1" })
hi(0, "WhichKeyIconGrey", { fg = "#4c566a" })
hi(0, "WhichKeyIconOrange", { fg = "#d08770" })
hi(0, "WhichKeyIconPurple", { fg = "#b48ead" })
hi(0, "Whitespace", { fg = "#434c5e" })
hi(0, "WildMenu", { bg = "#3b4252", fg = "#88c0d0" })
hi(0, "WinBar", { bg = "#2e3440" })
hi(0, "WinBarNC", { bg = "#2e3440" })
hi(0, "WinSeparator", { fg = "#3b4252" })
hi(0, "WinbarFilename", { bg = "#2e3440", fg = "#616e88" })
hi(0, "WinbarModified", { bg = "#2e3440", fg = "#bf616a" })
hi(0, "WinbarSearch", { bg = "#2e3440", fg = "#616e88" })
hi(0, "debugBreakpoint", { bg = "#333c4b", fg = "#81a1c1" })
hi(0, "debugPC", { bg = "#475567" })
hi(0, "diffAdded", { link = "DiffAdd" })
hi(0, "diffChanged", { link = "DiffChange" })
hi(0, "diffRemoved", { link = "DiffDelete" })
hi(0, "fzf1", { bg = "#565656", ctermbg = 8, ctermfg = 1, fg = "#e12672" })
hi(0, "fzf2", { bg = "#565656", ctermbg = 8, ctermfg = 2, fg = "#bcddbd" })
hi(0, "fzf3", { bg = "#565656", ctermbg = 8, ctermfg = 7, fg = "#d9d9d9" })
hi(0, "healthError", { fg = "#bf616a" })
hi(0, "healthSuccess", { fg = "#a3be8c" })
hi(0, "healthWarning", { fg = "#ebcb8b" })
hi(0, "htmlH1", { bold = true, fg = "#88c0d0" })
hi(0, "htmlH2", { fg = "#88c0d0" })
hi(0, "lCursor", { bg = "#d8dee9" })
hi(0, "markdownBlockquote", { fg = "#8fbcbb" })
hi(0, "markdownCode", { fg = "#8fbcbb" })
hi(0, "markdownCodeBlock", { fg = "#d8dee9" })
hi(0, "markdownFootnote", { fg = "#8fbcbb" })
hi(0, "markdownH1", { bold = true, fg = "#88c0d0" })
hi(0, "markdownH2", { fg = "#88c0d0" })
hi(0, "markdownHeadingDelimiter", { fg = "#8fbcbb" })
hi(0, "markdownId", { fg = "#8fbcbb" })
hi(0, "markdownIdDeclaration", { fg = "#8fbcbb" })
hi(0, "markdownLinkText", { fg = "#88c0d0", underline = true })
hi(0, "markdownUrl", { fg = "#d8dee9" })
hi(0, "qfFileName", { fg = "#88c0d0" })
hi(0, "qfLineNr", { fg = "#81a1c1" })
hi(0, "rainbowcol1", { fg = "#81a1c1" })
hi(0, "rainbowcol2", { fg = "#a3be8c" })
hi(0, "rainbowcol3", { fg = "#bf616a" })
hi(0, "rainbowcol4", { fg = "#ebcb8b" })
hi(0, "rainbowcol5", { fg = "#8fbcbb" })
hi(0, "rainbowcol6", { fg = "#b48ead" })
hi(0, "rainbowcol7", { fg = "#d8dee9" })
-- User
hi(0, "@markup.italic", { fg = "#88c0d0", italic = true })
hi(0, "@markup.strong", { bold = true, fg = "#81a1c1" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#3b4252"
g.terminal_color_1 = "#bf616a"
g.terminal_color_2 = "#a3be8c"
g.terminal_color_3 = "#ebcb8b"
g.terminal_color_4 = "#81a1c1"
g.terminal_color_5 = "#b48ead"
g.terminal_color_6 = "#88c0d0"
g.terminal_color_7 = "#e5e9f0"
g.terminal_color_8 = "#4c566a"
g.terminal_color_9 = "#bf616a"
g.terminal_color_10 = "#a3be8c"
g.terminal_color_11 = "#ebcb8b"
g.terminal_color_12 = "#81a1c1"
g.terminal_color_13 = "#b48ead"
g.terminal_color_14 = "#8fbcbb"
g.terminal_color_15 = "#eceff4"
