# OneDark.nvim — style = "warmer"
# Inspired by: navarasu/onedark.nvim

[colors.primary]
background = "#232326"
foreground = "#a7aab0"

[colors.cursor]
cursor = "#57a5e5"
text   = "#232326"

[colors.selection]
background = "#35363b"
text       = "#a7aab0"

[colors.normal]
black   = "#101012"
red     = "#de5d68"
green   = "#8fb573"
yellow  = "#dbb671"
blue    = "#57a5e5"
magenta = "#bb70d2"
cyan    = "#51a8b3"
white   = "#a7aab0"

[colors.bright]
black   = "#5a5b5e"
red     = "#de5d68"
green   = "#8fb573"
yellow  = "#e2c792"
blue    = "#68aee8"
magenta = "#bb70d2"
cyan    = "#51a8b3"
white   = "#818387"

[colors.dim]
black   = "#1b1c1e"
red     = "#833b3b"
green   = "#2b5d63"
yellow  = "#7c5c20"
blue    = "#1a2a37"
magenta = "#79428a"
cyan    = "#2b5d63"
white   = "#5a5b5e"

# Last Modified: Sun, 11 Jan 2026 01:28:31 AM
