#!/bin/sh

theme restore
xrate
setwallpaper &
dwmblocks &
# emacs --daemon &

autostart="mpd picom dunst unclutter"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

dbus-update-activation-environment --all
dbus-launch --exit-with-session ssh-agent dwm
